"""Research-only trade-candidate layer for probabilistic K2 diagnostics.

Candidate score definition:
``research_confidence = expansion_prob * directional_confidence
* min(1, abs(directional_prob_up - directional_prob_down) / min_directional_asymmetry)``.

Candidate decisions use only timestamp-local model/regime inputs and prior
walk-forward validation rows from the same regime/probability-decile cell. Any
forward-return or target columns written to the output are ex-post diagnostics
and are not used by the action gate.
"""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from k2_systematic_macro.csv_export import write_research_csv
from k2_systematic_macro.data.dataset import ResearchDataset


TRADE_CANDIDATE_DISCLAIMER = (
    "Research-only trade candidates. These rows are not live trade signals, "
    "execution instructions, backtests, capital allocation, or position sizing."
)


@dataclass(frozen=True)
class TradeCandidateConfig:
    """Conservative gates for exploratory candidate generation."""

    horizon: str = "1d"
    expansion_probability_min: float = 0.60
    expansion_decile_min: int = 8
    min_cell_n: int = 30
    top_cells: int = 5
    require_prior_top_cell: bool = True
    min_directional_confidence: float = 0.55
    min_directional_asymmetry: float = 0.10
    min_expected_move_atr: float = 0.0
    diagnostics_fail_blocks: bool = True
    regime2_policy: str = "risk_off_no_entry"
    latest_examples: int = 10


@dataclass(frozen=True)
class TradeCandidateArtifacts:
    """Files generated by the trade-candidate research layer."""

    paths: dict[str, Path]
    summary: dict[str, Any]


def build_trade_candidates(
    *,
    primary_panel: pd.DataFrame,
    predictions: pd.DataFrame,
    diagnostics_harness: pd.DataFrame,
    symbol: str,
    config: TradeCandidateConfig | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Build timestamped long/short/no-trade research candidates.

    The gate is expansion-first: current expansion probability and probability
    decile must be high enough before prior-cell directional asymmetry is used.
    Prior-cell diagnostics are shifted by timestamp to avoid using the row's own
    forward label in the candidate decision.
    """

    cfg = config or TradeCandidateConfig()
    joined = _candidate_input_panel(primary_panel, predictions, symbol, cfg.horizon)
    if joined.empty:
        empty_candidates = _empty_candidates()
        empty_diagnostics = _empty_directional_diagnostics()
        return empty_candidates, empty_diagnostics

    prior = _prior_cell_diagnostics(joined, cfg)
    work = joined.merge(
        prior["row_diagnostics"],
        on="_row_id",
        how="left",
        suffixes=("", "_prior"),
    )
    diagnostics_status = _diagnostics_status(diagnostics_harness)
    fail_blocks = bool(cfg.diagnostics_fail_blocks and diagnostics_status == "FAIL")

    rows: list[dict[str, Any]] = []
    for row in work.sort_values("ts").to_dict(orient="records"):
        candidate = _candidate_row(row, cfg, diagnostics_status, fail_blocks)
        rows.append(candidate)
    candidates = pd.DataFrame(rows)
    if not candidates.empty:
        candidates = candidates.sort_values("timestamp").reset_index(drop=True)
    return candidates, prior["cell_diagnostics"]


def build_trade_candidate_artifacts(
    *,
    output_dir: Path,
    dataset: ResearchDataset,
    primary_panel: pd.DataFrame,
    predictions: pd.DataFrame,
    diagnostics_harness: pd.DataFrame,
    model_kind: str,
    config: TradeCandidateConfig | None = None,
) -> TradeCandidateArtifacts:
    """Write CSV, JSON, markdown, and chart artifacts for trade candidates."""

    cfg = config or TradeCandidateConfig()
    graphics_dir = output_dir / "graphics"
    graphics_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}

    candidates, directional = build_trade_candidates(
        primary_panel=primary_panel,
        predictions=predictions,
        diagnostics_harness=diagnostics_harness,
        symbol=dataset.symbol,
        config=cfg,
    )
    summary_by_action = _summary_by_action_regime_decile(candidates)
    latest_examples = _latest_examples(candidates, cfg.latest_examples)
    summary = _candidate_summary_payload(
        output_dir=output_dir,
        candidates=candidates,
        directional=directional,
        summary_by_action=summary_by_action,
        latest_examples=latest_examples,
        config=cfg,
        model_kind=model_kind,
    )

    paths["trade_candidates"] = _write_frame(candidates, output_dir / "trade_candidates.csv")
    paths["trade_candidates_json"] = _write_json(
        output_dir / "trade_candidates.json",
        {
            "disclaimer": TRADE_CANDIDATE_DISCLAIMER,
            "config": asdict(cfg),
            "candidates": candidates.to_dict(orient="records"),
        },
    )
    paths["trade_candidate_directional_diagnostics"] = _write_frame(
        directional,
        output_dir / "trade_candidate_directional_diagnostics.csv",
    )
    paths["trade_candidate_summary"] = _write_frame(
        summary_by_action,
        output_dir / "trade_candidate_summary_by_action_regime_decile.csv",
    )
    paths["trade_candidate_examples"] = _write_json(
        output_dir / "trade_candidate_latest_examples.json",
        latest_examples,
    )
    paths["trade_candidate_timeline_chart"] = _plot_candidate_timeline(
        candidates,
        graphics_dir / "trade_candidate_timeline.png",
        dataset,
        model_kind,
    )
    paths["trade_candidate_counts_chart"] = _plot_candidate_counts(
        candidates,
        graphics_dir / "trade_candidate_counts_by_regime_decile.png",
        dataset,
    )
    paths["trade_candidate_asymmetry_chart"] = _plot_asymmetry_distribution(
        candidates,
        graphics_dir / "trade_candidate_asymmetry_distribution.png",
        dataset,
    )
    paths["trade_candidate_forward_outcome_chart"] = _plot_forward_outcomes(
        candidates,
        graphics_dir / "trade_candidate_forward_outcomes.png",
        dataset,
    )
    paths["trade_candidate_report"] = _write_text(
        output_dir / "trade_candidate_report.md",
        _render_trade_candidate_report(summary, paths, output_dir),
    )
    return TradeCandidateArtifacts(paths=paths, summary=summary)


def _candidate_input_panel(
    primary_panel: pd.DataFrame,
    predictions: pd.DataFrame,
    symbol: str,
    horizon: str,
) -> pd.DataFrame:
    if primary_panel.empty or predictions.empty:
        return pd.DataFrame()
    suffix = horizon.lower().replace(" ", "_")
    keep = [
        "ts",
        "symbol",
        "c",
        "regime",
        "regime_probability",
        "target_future_log_return_" + suffix,
        "target_future_return_" + suffix,
        "target_future_move_norm_" + suffix,
        "target_future_vol_expansion_" + suffix,
        "target_vol_expansion_event_" + suffix,
        "target_tail_event_" + suffix,
        "target_conditional_direction_" + suffix,
    ]
    atr_cols = [col for col in primary_panel.columns if col.startswith("atr_")]
    feature_cols = [col for col in keep if col in primary_panel] + atr_cols[:1]
    panel = primary_panel[feature_cols].copy()
    out = predictions.merge(panel, on="ts", how="left", suffixes=("", "_panel"))
    if "symbol" not in out:
        out["symbol"] = symbol
    out["symbol"] = out["symbol"].fillna(symbol)
    out["ts"] = pd.to_datetime(out["ts"], utc=True, errors="coerce")
    out["close"] = pd.to_numeric(out.get("c"), errors="coerce")
    out["regime"] = pd.to_numeric(out.get("regime"), errors="coerce")
    out["expansion_prob"] = pd.to_numeric(out.get("y_prob"), errors="coerce")
    out["expansion_decile"] = (
        pd.qcut(out["expansion_prob"].rank(method="first"), q=10, labels=False, duplicates="drop")
        .astype(float)
        .add(1)
    )
    out = out.dropna(subset=["ts", "regime", "expansion_prob", "expansion_decile"])
    out = out.sort_values("ts").reset_index(drop=True)
    out["_row_id"] = np.arange(out.shape[0])
    return out


def _prior_cell_diagnostics(frame: pd.DataFrame, config: TradeCandidateConfig) -> dict[str, pd.DataFrame]:
    row_rows: list[dict[str, Any]] = []
    cell_rows: list[dict[str, Any]] = []
    work = frame.sort_values("ts").reset_index(drop=True)
    for idx, row in work.iterrows():
        prior = work.iloc[:idx]
        regime = int(row["regime"])
        decile = int(row["expansion_decile"])
        cell_stats = _cell_diagnostics(prior, config)
        cell_rows.extend(
            {
                "asof_timestamp": row["ts"].isoformat(),
                **stats,
            }
            for stats in cell_stats
        )
        selected = _select_prior_top_cells(pd.DataFrame(cell_stats), config)
        current = _find_cell_stats(cell_stats, regime, decile)
        selected_rank = _selected_rank(selected, regime, decile)
        row_rows.append(
            {
                "_row_id": int(row["_row_id"]),
                "prior_cell_n": current.get("cell_n"),
                "prior_expansion_n": current.get("expansion_cell_n"),
                "prior_cell_event_rate": current.get("event_rate"),
                "directional_prob_up": current.get("directional_prob_up"),
                "directional_prob_down": current.get("directional_prob_down"),
                "expected_upside_move_atr": current.get("expected_upside_move_atr"),
                "expected_downside_move_atr": current.get("expected_downside_move_atr"),
                "expected_move_atr": current.get("expected_move_atr"),
                "upside_downside_asymmetry": current.get("upside_downside_asymmetry"),
                "directional_asymmetry": current.get("directional_asymmetry"),
                "prior_convexity_research_score": current.get("convexity_research_score"),
                "prior_top_cell_rank": selected_rank,
                "prior_top_cell": selected_rank is not None,
            }
        )
    row_diag = pd.DataFrame(row_rows)
    cell_diag = pd.DataFrame(cell_rows)
    if not cell_diag.empty:
        cell_diag = cell_diag.drop_duplicates(["asof_timestamp", "regime", "expansion_decile"])
    return {"row_diagnostics": row_diag, "cell_diagnostics": cell_diag}


def _cell_diagnostics(frame: pd.DataFrame, config: TradeCandidateConfig) -> list[dict[str, Any]]:
    if frame.empty:
        return []
    suffix = config.horizon.lower().replace(" ", "_")
    event_col = "target_vol_expansion_event_" + suffix
    move_col = "target_future_move_norm_" + suffix
    return_col = "target_future_log_return_" + suffix
    tail_col = "target_tail_event_" + suffix
    rows: list[dict[str, Any]] = []
    for (regime, decile), group in frame.groupby(["regime", "expansion_decile"], dropna=True):
        event = _numeric_col(group, event_col)
        move = _numeric_col(group, move_col)
        fwd = _numeric_col(group, return_col)
        expansion = event.eq(1.0)
        expansion_group = group.loc[expansion]
        expansion_move = move.loc[expansion]
        up = expansion_move.gt(0)
        down = expansion_move.lt(0)
        up_n = int(up.sum())
        down_n = int(down.sum())
        expansion_n = int(expansion.sum())
        prob_up = float(up_n / expansion_n) if expansion_n else np.nan
        prob_down = float(down_n / expansion_n) if expansion_n else np.nan
        upside = _safe(expansion_move[up].mean())
        downside = _safe((-expansion_move[down]).mean())
        expected_move = _safe(expansion_move.abs().mean())
        directional_asymmetry = (
            float(prob_up - prob_down) if not pd.isna(prob_up) and not pd.isna(prob_down) else np.nan
        )
        payoff_asymmetry = (
            float((upside - downside) / (upside + downside))
            if upside is not None and downside is not None and (upside + downside) > 0
            else np.nan
        )
        event_rate = _safe(event.mean())
        mean_probability = _safe(_numeric_col(group, "expansion_prob").mean())
        tail_participation = _safe(_numeric_col(group, tail_col).mean())
        drawdown_proxy = _safe(_max_drawdown(fwd.dropna()))
        rows.append(
            {
                "regime": int(regime),
                "expansion_decile": int(decile),
                "cell_n": int(group.shape[0]),
                "expansion_cell_n": expansion_n,
                "event_rate": event_rate,
                "mean_probability": mean_probability,
                "tail_participation": tail_participation,
                "drawdown_proxy": drawdown_proxy,
                "directional_prob_up": prob_up,
                "directional_prob_down": prob_down,
                "expected_upside_move_atr": upside,
                "expected_downside_move_atr": downside,
                "expected_move_atr": expected_move,
                "upside_downside_asymmetry": payoff_asymmetry,
                "directional_asymmetry": directional_asymmetry,
                "convexity_research_score": _convexity_score(
                    event_rate,
                    mean_probability,
                    tail_participation,
                    drawdown_proxy,
                ),
                "expansion_return_rows": int(expansion_group.shape[0]),
            }
        )
    return rows


def _select_prior_top_cells(cells: pd.DataFrame, config: TradeCandidateConfig) -> pd.DataFrame:
    if cells.empty:
        return pd.DataFrame()
    work = cells[pd.to_numeric(cells["cell_n"], errors="coerce") >= config.min_cell_n].copy()
    if work.empty:
        return pd.DataFrame()
    work = work.sort_values(
        ["event_rate", "mean_probability", "convexity_research_score", "cell_n", "regime", "expansion_decile"],
        ascending=[False, False, False, False, True, False],
        kind="mergesort",
    ).head(config.top_cells)
    work = work.reset_index(drop=True)
    work.insert(0, "prior_top_cell_rank", np.arange(1, work.shape[0] + 1))
    return work


def _candidate_row(
    row: dict[str, Any],
    config: TradeCandidateConfig,
    diagnostics_status: str,
    fail_blocks: bool,
) -> dict[str, Any]:
    reasons: list[str] = []
    regime = int(row["regime"])
    expansion_prob = _float(row.get("expansion_prob"))
    expansion_decile = _int(row.get("expansion_decile"))
    prior_cell_n = _int(row.get("prior_cell_n"))
    prob_up = _float(row.get("directional_prob_up"))
    prob_down = _float(row.get("directional_prob_down"))
    expected_up = _float(row.get("expected_upside_move_atr"))
    expected_down = _float(row.get("expected_downside_move_atr"))
    directional_asymmetry = _float(row.get("directional_asymmetry"))
    prior_top_cell = bool(row.get("prior_top_cell")) if not pd.isna(row.get("prior_top_cell")) else False

    if fail_blocks:
        reasons.append("diagnostics_fail")
    if config.regime2_policy == "risk_off_no_entry" and regime == 2:
        reasons.append("regime2_risk_off_no_entry")
    if expansion_prob is None or expansion_decile is None:
        reasons.append("missing_expansion_probability_or_decile")
    if prior_cell_n is None or prior_cell_n < config.min_cell_n:
        reasons.append("cell_sample_below_min")
    if config.require_prior_top_cell and not prior_top_cell:
        reasons.append("not_prior_top_cell")
    if expansion_prob is not None and expansion_prob < config.expansion_probability_min:
        reasons.append("expansion_probability_below_threshold")
    if expansion_decile is not None and expansion_decile < config.expansion_decile_min:
        reasons.append("expansion_decile_below_min")
    directional_confidence = _max_or_none(prob_up, prob_down)
    if directional_confidence is None or directional_confidence < config.min_directional_confidence:
        reasons.append("directional_confidence_below_threshold")
    if directional_asymmetry is None or abs(directional_asymmetry) < config.min_directional_asymmetry:
        reasons.append("directional_asymmetry_below_threshold")

    action = "no_trade"
    if not reasons:
        if directional_asymmetry is not None and directional_asymmetry > 0:
            if expected_up is not None and expected_up >= config.min_expected_move_atr:
                action = "long_candidate"
            else:
                reasons.append("expected_upside_move_below_threshold")
        elif directional_asymmetry is not None and directional_asymmetry < 0:
            if expected_down is not None and expected_down >= config.min_expected_move_atr:
                action = "short_candidate"
            else:
                reasons.append("expected_downside_move_below_threshold")
        else:
            reasons.append("no_directional_edge")

    overlay_multiplier = 1.0
    if config.regime2_policy == "size_down_50pct" and regime == 2:
        overlay_multiplier = 0.5
    confidence = _confidence_score(expansion_prob, directional_confidence, directional_asymmetry, config)
    return {
        "timestamp": pd.Timestamp(row["ts"]).isoformat(),
        "symbol": row.get("symbol"),
        "close": _float(row.get("close")),
        "regime": regime,
        "expansion_prob": expansion_prob,
        "expansion_decile": expansion_decile,
        "prior_cell_n": prior_cell_n,
        "prior_expansion_n": _int(row.get("prior_expansion_n")),
        "prior_top_cell_rank": _int(row.get("prior_top_cell_rank")),
        "prior_top_cell": prior_top_cell,
        "directional_prob_up": prob_up,
        "directional_prob_down": prob_down,
        "expected_move_atr": _float(row.get("expected_move_atr")),
        "expected_upside_move_atr": expected_up,
        "expected_downside_move_atr": expected_down,
        "upside_downside_asymmetry": _float(row.get("upside_downside_asymmetry")),
        "directional_asymmetry": directional_asymmetry,
        "convexity_research_score": _float(row.get("prior_convexity_research_score")),
        "diagnostics_status": diagnostics_status,
        "regime2_policy": config.regime2_policy,
        "confidence_overlay_multiplier": overlay_multiplier,
        "action": action if not reasons else "no_trade",
        "research_confidence": confidence,
        "reason_codes": "pass" if not reasons else "|".join(reasons),
        "expost_target_vol_expansion_event_1d": _float(row.get("target_vol_expansion_event_1d")),
        "expost_forward_return_1d": _float(row.get("target_future_return_1d")),
        "expost_forward_log_return_1d": _float(row.get("target_future_log_return_1d")),
        "expost_forward_move_atr_1d": _float(row.get("target_future_move_norm_1d")),
    }


def _diagnostics_status(harness: pd.DataFrame) -> str:
    if harness.empty or "status" not in harness:
        return "WARN"
    statuses = {str(value).upper() for value in harness["status"].dropna()}
    if "FAIL" in statuses:
        return "FAIL"
    if "WARN" in statuses:
        return "WARN"
    return "PASS"


def _summary_by_action_regime_decile(candidates: pd.DataFrame) -> pd.DataFrame:
    columns = ["action", "regime", "expansion_decile", "n", "mean_confidence", "mean_forward_return_1d"]
    if candidates.empty:
        return pd.DataFrame(columns=columns)
    grouped = (
        candidates.groupby(["action", "regime", "expansion_decile"], dropna=False)
        .agg(
            n=("action", "size"),
            mean_confidence=("research_confidence", "mean"),
            mean_forward_return_1d=("expost_forward_return_1d", "mean"),
        )
        .reset_index()
    )
    return grouped.sort_values(["action", "regime", "expansion_decile"]).reset_index(drop=True)


def _latest_examples(candidates: pd.DataFrame, n: int) -> dict[str, Any]:
    if candidates.empty:
        return {"disclaimer": TRADE_CANDIDATE_DISCLAIMER, "examples": []}
    live = candidates[candidates["action"].isin(["long_candidate", "short_candidate"])]
    source = live if not live.empty else candidates
    return {
        "disclaimer": TRADE_CANDIDATE_DISCLAIMER,
        "examples": source.sort_values("timestamp").tail(n).to_dict(orient="records"),
    }


def _candidate_summary_payload(
    *,
    output_dir: Path,
    candidates: pd.DataFrame,
    directional: pd.DataFrame,
    summary_by_action: pd.DataFrame,
    latest_examples: dict[str, Any],
    config: TradeCandidateConfig,
    model_kind: str,
) -> dict[str, Any]:
    counts = candidates["action"].value_counts().to_dict() if not candidates.empty else {}
    return {
        "artifact_path": str(output_dir),
        "disclaimer": TRADE_CANDIDATE_DISCLAIMER,
        "model_kind": model_kind,
        "config": asdict(config),
        "action_counts": {str(key): int(value) for key, value in counts.items()},
        "candidate_rows": int(candidates.shape[0]),
        "directional_diagnostic_rows": int(directional.shape[0]),
        "summary_by_action_regime_decile": summary_by_action.to_dict(orient="records"),
        "latest_examples": latest_examples.get("examples", []),
        "score_definition": (
            "research_confidence = expansion_prob * directional_confidence * "
            "min(1, abs(directional_prob_up - directional_prob_down) / "
            "min_directional_asymmetry); diagnostic only, not sizing."
        ),
    }


def _render_trade_candidate_report(summary: dict[str, Any], paths: dict[str, Path], output_dir: Path) -> str:
    rel = {key: str(path.relative_to(output_dir)) for key, path in paths.items()}
    counts = summary.get("action_counts", {})
    lines = [
        "# CL Trade-Candidate Research Report",
        "",
        TRADE_CANDIDATE_DISCLAIMER,
        "",
        "## Candidate Logic",
        "",
        "- Expansion-first gate: current expansion probability and probability decile must clear configured thresholds.",
        "- Direction gate: prior rows from the same regime/probability-decile cell estimate conditional up/down probabilities and ATR-normalized payoff asymmetry.",
        "- Diagnostics gate: any diagnostics harness `FAIL` suppresses all candidates.",
        "- Regime 2 overlay defaults to risk-off/no-entry.",
        "- Forward outcomes in these artifacts are ex-post diagnostics only and are not used to assign actions.",
        "",
        "## Counts",
        "",
        f"- Action counts: `{counts}`",
        f"- Candidate rows scored: `{summary.get('candidate_rows')}`",
        f"- Directional diagnostic rows: `{summary.get('directional_diagnostic_rows')}`",
        f"- Score definition: {summary.get('score_definition')}",
        "",
        "## Artifacts",
        "",
        f"- Candidates CSV: `{rel['trade_candidates']}`",
        f"- Candidates JSON: `{rel['trade_candidates_json']}`",
        f"- Directional diagnostics: `{rel['trade_candidate_directional_diagnostics']}`",
        f"- Summary: `{rel['trade_candidate_summary']}`",
        f"- Latest examples: `{rel['trade_candidate_examples']}`",
        f"- Charts: `graphics/{Path(rel['trade_candidate_timeline_chart']).name}`, `graphics/{Path(rel['trade_candidate_counts_chart']).name}`, `graphics/{Path(rel['trade_candidate_asymmetry_chart']).name}`, `graphics/{Path(rel['trade_candidate_forward_outcome_chart']).name}`",
        "",
        "## Latest Examples",
        "",
    ]
    examples = summary.get("latest_examples") or []
    if not examples:
        lines.append("- No candidate examples were available.")
    else:
        for row in examples[-5:]:
            lines.append(
                "- `{timestamp}` action `{action}`, regime `{regime}`, decile `{decile}`, "
                "confidence `{confidence}`, reasons `{reasons}`.".format(
                    timestamp=row.get("timestamp"),
                    action=row.get("action"),
                    regime=row.get("regime"),
                    decile=row.get("expansion_decile"),
                    confidence=_fmt(row.get("research_confidence")),
                    reasons=row.get("reason_codes"),
                )
            )
    return "\n".join(lines) + "\n"


def _plot_candidate_timeline(
    candidates: pd.DataFrame,
    path: Path,
    dataset: ResearchDataset,
    model_kind: str,
) -> Path:
    fig, ax = _figure(figsize=(10, 5))
    if not candidates.empty:
        work = candidates.copy()
        work["timestamp"] = pd.to_datetime(work["timestamp"], utc=True, errors="coerce")
        ax.plot(work["timestamp"], work["close"], color="black", linewidth=1, label="Close")
        for action, marker, color in [
            ("long_candidate", "^", "tab:green"),
            ("short_candidate", "v", "tab:red"),
        ]:
            subset = work[work["action"] == action]
            if not subset.empty:
                ax.scatter(subset["timestamp"], subset["close"], marker=marker, color=color, label=action)
        ax.legend()
    ax.set_title("Trade-Candidate Timeline Over Price")
    ax.set_xlabel("Timestamp")
    ax.set_ylabel("Close")
    _caption(fig, dataset, f"Source: {model_kind} expansion predictions; research candidates only")
    return _save(fig, path)


def _plot_candidate_counts(candidates: pd.DataFrame, path: Path, dataset: ResearchDataset) -> Path:
    fig, ax = _figure(figsize=(9, 5))
    if not candidates.empty:
        work = candidates[candidates["action"].isin(["long_candidate", "short_candidate"])]
        if work.empty:
            work = candidates
        labels = work["regime"].astype(str) + "/D" + work["expansion_decile"].astype(str)
        counts = labels.value_counts().sort_index()
        ax.bar(counts.index, counts.to_numpy())
        ax.tick_params(axis="x", rotation=45)
    ax.set_title("Candidate Counts by Regime and Probability Decile")
    ax.set_xlabel("Regime/decile")
    ax.set_ylabel("Rows")
    _caption(fig, dataset, "Source: trade-candidate research output")
    return _save(fig, path)


def _plot_asymmetry_distribution(candidates: pd.DataFrame, path: Path, dataset: ResearchDataset) -> Path:
    fig, ax = _figure(figsize=(8, 4.8))
    if not candidates.empty:
        values = pd.to_numeric(candidates["directional_asymmetry"], errors="coerce").dropna()
        if not values.empty:
            ax.hist(values, bins=20)
            ax.axvline(0.0, color="black", linestyle="--", linewidth=1)
    ax.set_title("Prior-Cell Directional Asymmetry Distribution")
    ax.set_xlabel("P(up | expansion, cell) - P(down | expansion, cell)")
    ax.set_ylabel("Rows")
    _caption(fig, dataset, "Source: prior walk-forward validation rows by regime/decile")
    return _save(fig, path)


def _plot_forward_outcomes(candidates: pd.DataFrame, path: Path, dataset: ResearchDataset) -> Path:
    fig, ax = _figure(figsize=(8, 4.8))
    if not candidates.empty and "expost_forward_return_1d" in candidates:
        work = candidates.dropna(subset=["expost_forward_return_1d"])
        if not work.empty:
            means = work.groupby("action")["expost_forward_return_1d"].mean().sort_index()
            ax.bar(means.index, means.to_numpy())
            ax.axhline(0.0, color="black", linestyle="--", linewidth=1)
    ax.set_title("Ex-Post 1d Forward Outcome Diagnostics by Action")
    ax.set_xlabel("Action")
    ax.set_ylabel("Mean forward return")
    _caption(fig, dataset, "Forward outcomes are diagnostic labels, not candidate inputs")
    return _save(fig, path)


def _empty_candidates() -> pd.DataFrame:
    return pd.DataFrame(
        columns=[
            "timestamp",
            "symbol",
            "close",
            "regime",
            "expansion_prob",
            "expansion_decile",
            "directional_prob_up",
            "directional_prob_down",
            "expected_move_atr",
            "upside_downside_asymmetry",
            "convexity_research_score",
            "diagnostics_status",
            "action",
            "research_confidence",
            "reason_codes",
        ]
    )


def _empty_directional_diagnostics() -> pd.DataFrame:
    return pd.DataFrame(
        columns=[
            "asof_timestamp",
            "regime",
            "expansion_decile",
            "cell_n",
            "directional_prob_up",
            "directional_prob_down",
            "expected_upside_move_atr",
            "expected_downside_move_atr",
            "upside_downside_asymmetry",
        ]
    )


def _find_cell_stats(stats: list[dict[str, Any]], regime: int, decile: int) -> dict[str, Any]:
    for row in stats:
        if int(row["regime"]) == regime and int(row["expansion_decile"]) == decile:
            return row
    return {}


def _selected_rank(selected: pd.DataFrame, regime: int, decile: int) -> int | None:
    if selected.empty:
        return None
    hit = selected[(selected["regime"] == regime) & (selected["expansion_decile"] == decile)]
    if hit.empty:
        return None
    return int(hit.iloc[0]["prior_top_cell_rank"])


def _convexity_score(
    event_rate: float | None,
    mean_probability: float | None,
    tail_participation: float | None,
    drawdown_proxy: float | None,
) -> float | None:
    if event_rate is None or mean_probability is None:
        return None
    tail = 0.0 if tail_participation is None or pd.isna(tail_participation) else float(tail_participation)
    drawdown = 0.0 if drawdown_proxy is None or pd.isna(drawdown_proxy) else abs(float(drawdown_proxy))
    return float(event_rate) + float(mean_probability) + tail - drawdown


def _confidence_score(
    expansion_prob: float | None,
    directional_confidence: float | None,
    directional_asymmetry: float | None,
    config: TradeCandidateConfig,
) -> float | None:
    if expansion_prob is None or directional_confidence is None or directional_asymmetry is None:
        return None
    threshold = max(config.min_directional_asymmetry, 1e-9)
    asymmetry_scale = min(1.0, abs(directional_asymmetry) / threshold)
    return float(expansion_prob * directional_confidence * asymmetry_scale)


def _max_drawdown(returns: pd.Series) -> float:
    if returns.empty:
        return np.nan
    equity = np.exp(returns.cumsum())
    return float((equity / equity.cummax() - 1.0).min())


def _numeric_col(frame: pd.DataFrame, col: str) -> pd.Series:
    if col not in frame:
        return pd.Series(np.nan, index=frame.index, dtype=float)
    return pd.to_numeric(frame[col], errors="coerce")


def _max_or_none(left: float | None, right: float | None) -> float | None:
    values = [value for value in [left, right] if value is not None and not pd.isna(value)]
    return max(values) if values else None


def _safe(value: Any) -> float | None:
    if value is None or pd.isna(value):
        return None
    return float(value)


def _float(value: Any) -> float | None:
    if value is None or pd.isna(value):
        return None
    return float(value)


def _int(value: Any) -> int | None:
    if value is None or pd.isna(value):
        return None
    return int(value)


def _fmt(value: Any) -> str:
    if value is None or pd.isna(value):
        return "NA"
    return f"{float(value):.4f}"


def _figure(figsize: tuple[float, float] = (8, 4.8)):
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=figsize)
    ax.grid(True, axis="y", alpha=0.25)
    return fig, ax


def _caption(fig, dataset: ResearchDataset, text: str) -> None:
    rng = dataset.metadata.get("bar_ranges", {}).get(dataset.primary_timeframe, {})
    fig.text(
        0.01,
        0.01,
        f"{text}. Time range: {rng.get('start_ts')} to {rng.get('end_ts')}.",
        fontsize=8,
    )


def _save(fig, path: Path) -> Path:
    fig.tight_layout(rect=(0, 0.05, 1, 1))
    fig.savefig(path, dpi=160)
    import matplotlib.pyplot as plt

    plt.close(fig)
    return path


def _write_frame(frame: pd.DataFrame, path: Path) -> Path:
    return write_research_csv(frame, path)


def _write_json(path: Path, payload: Any) -> Path:
    path.write_text(json.dumps(payload, indent=2, default=str))
    return path


def _write_text(path: Path, text: str) -> Path:
    path.write_text(text)
    return path
