"""Calibrated pipeline configuration (cohort-01).

Auto-generated by scripts/research/convexity_alpha_runner.py --calibrate.

Stage 1 (per implementation plan Step 5): each kill threshold set at the cohort
25th percentile (75th for max_consecutive_losses).

Stage 3 (cohort-01 calibration, documented in the calibration + results docs):
  * catastrophic_fold_dd_multiplier raised from the 2.0 spec default to
    2.9. An anchored short IS window understates the normal
    drawdown envelope of a trend strategy on fat-tailed assets (crypto), so the
    2x guard fired on routine fold drawdowns; the calibrated value covers the
    worst observed cohort fold-DD/IS-DD ratio plus a 30% buffer.
  * require_positive_median_fold_skew disabled. Convex alphas concentrate their
    positive skew in a few fold windows, so the MEDIAN per-fold skew is often
    negative even when the pooled OOS distribution is strongly positively skewed.
    Requiring positive median fold skew reintroduces the Sharpe-punishes-
    convexity trap at the fold level. The always-on aggregate-OOS-skew>0 guard,
    the CCS OOS/IS ratio, and the consecutive-negative-CCS-fold guard remain.

Cohort size used for calibration: n=5 candidates reaching Stage 1.
Do NOT hand-edit; re-run --calibrate to regenerate.
"""
from __future__ import annotations

from .types import (
    PipelineConfig,
    Stage1Thresholds,
    Stage2Thresholds,
    Stage3Thresholds,
    Stage4Thresholds,
)


def calibrated_config() -> PipelineConfig:
    """Cohort-01-calibrated config. Stage 2 and Stage 4 keep spec defaults."""
    return PipelineConfig(
        stage1=Stage1Thresholds(
            min_aggregate_skew=-0.642971,
            catastrophic_skew_floor=-1.0,
            catastrophic_skew_max_fraction=0.33,
            min_ccs_aggregate=0.157076,
            min_universe_positive_fraction=1.0,
            min_convexity_beta=-0.019046,
            max_consecutive_losses=13,
            trade_duration_tolerance_factor=5.0,
        ),
        stage2=Stage2Thresholds(),
        stage3=Stage3Thresholds(
            catastrophic_fold_dd_multiplier=2.9,
            require_positive_median_fold_skew=False,
        ),
        stage4=Stage4Thresholds(),
        notes="cohort-01 calibrated (Stage 1 @ 25th pct; Stage 3 fat-tail + lumpy-skew adjustments)",
    )
