"""Render a ``volbook-futures-ohlcv.canvas.tsx`` with an inlined bundle.

The canvas skill forbids ``fetch()`` and external imports from the
canvas file, so we generate a fresh ``.canvas.tsx`` on every CLI run
with the full bundle JSON baked in as a ``const BUNDLE``. The React
app only needs to react to user selections — all the data is in-scope.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from .bundle import OhlcvBundle
from .contracts import FuturesSpec


# Simple placeholder substitution (no ``.format()``) so the JSX/TS braces
# in the body do not need to be escaped. Only ``__BUNDLE_JSON__`` and
# ``__GENERATED_AT__`` are replaced.
_TEMPLATE = r'''import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Button,
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Select,
  Stack,
  Stat,
  Table,
  Text,
  Toggle,
  useCanvasState,
  useHostTheme,
} from "cursor/canvas";

// Auto-generated by src/volbook/canvas_writer.py — do not hand-edit.
// Regenerate with: python -m scripts.volbook.fetch_futures_ohlcv

type Bar = { t: string; o: number; h: number; l: number; c: number; v: number };

type IndicatorRecord = {
  function: string;
  display_name: string;
  params: Record<string, number | string>;
  outputs: Record<string, Array<number | null>>;
  error: string | null;
};

type TradeSetup = {
  name: string;
  direction: "long" | "short";
  entry: number;
  stop: number;
  target: number;
  risk: number;
  reward: number;
  rr: number;
  confidence: number;
  score: number;
  rationale: string[];
  tags: string[];
};

type Series = {
  key: string;
  contract_key: string;
  contract_label: string;
  symbol: string;
  expiry: string;
  exchange: string;
  bar_size: string;
  duration: string;
  what_to_show: string;
  fetched_at: string;
  bars: Bar[];
  indicators: Record<string, IndicatorRecord[]>;
  setups: TradeSetup[];
};

const GENERATED_AT = "__GENERATED_AT__";
const BUNDLE: Series[] = __BUNDLE_JSON__;

// ── Helpers ───────────────────────────────────────────────────────────

function formatPrice(x: number): string {
  if (!Number.isFinite(x)) return "—";
  const abs = Math.abs(x);
  const digits = abs >= 1000 ? 2 : abs >= 100 ? 2 : abs >= 10 ? 3 : 4;
  return x.toLocaleString(undefined, {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}

function formatPct(x: number): string {
  if (!Number.isFinite(x)) return "—";
  const sign = x > 0 ? "+" : "";
  return `${sign}${(x * 100).toFixed(2)}%`;
}

function formatVolume(v: number): string {
  if (!Number.isFinite(v)) return "—";
  const abs = Math.abs(v);
  if (abs >= 1e9) return `${(v / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${(v / 1e6).toFixed(2)}M`;
  if (abs >= 1e3) return `${(v / 1e3).toFixed(1)}k`;
  return v.toFixed(0);
}

function shortLabel(iso: string, barSize: string): string {
  if (!iso) return "";
  const m = iso.match(/^(\d{4})-(\d{2})-(\d{2})(?:[T ](\d{2}):(\d{2}))?/);
  if (!m) return iso;
  const [, , mm, dd, hh, mi] = m;
  const daily = /day|week|month/i.test(barSize);
  if (daily) return `${mm}-${dd}`;
  if (hh && mi) return `${mm}-${dd} ${hh}:${mi}`;
  return `${mm}-${dd}`;
}

function annualizer(barSize: string): number {
  const s = barSize.toLowerCase();
  if (s.includes("day") || s.includes("week") || s.includes("month")) return Math.sqrt(252);
  if (s.includes("hour")) return Math.sqrt(252 * 6.5);
  const mins = parseInt(s, 10);
  if (Number.isFinite(mins) && mins > 0) return Math.sqrt((252 * 6.5 * 60) / mins);
  return Math.sqrt(252);
}

function realizedVol(bars: Bar[], window: number, barSize: string): number {
  if (bars.length < 2) return NaN;
  const tail = bars.slice(Math.max(0, bars.length - (window + 1)));
  const rets: number[] = [];
  for (let i = 1; i < tail.length; i++) {
    const r = Math.log(tail[i].c / tail[i - 1].c);
    if (Number.isFinite(r)) rets.push(r);
  }
  if (rets.length < 2) return NaN;
  const mean = rets.reduce((a, b) => a + b, 0) / rets.length;
  const variance =
    rets.reduce((a, b) => a + (b - mean) * (b - mean), 0) / (rets.length - 1);
  return Math.sqrt(variance) * annualizer(barSize);
}

function uniqueOrdered<T>(xs: T[]): T[] {
  const seen = new Set<string>();
  const out: T[] = [];
  for (const x of xs) {
    const k = String(x);
    if (!seen.has(k)) {
      seen.add(k);
      out.push(x);
    }
  }
  return out;
}

// "Nice" axis ticks — 1/2/5 × 10^k steps.
function niceTicks(min: number, max: number, count: number): number[] {
  const range = max - min;
  if (!Number.isFinite(range) || range <= 0) return [min];
  const rough = range / Math.max(1, count);
  const pow = Math.pow(10, Math.floor(Math.log10(rough)));
  const frac = rough / pow;
  const niceFrac = frac < 1.5 ? 1 : frac < 3 ? 2 : frac < 7 ? 5 : 10;
  const step = niceFrac * pow;
  const first = Math.ceil(min / step) * step;
  const out: number[] = [];
  for (let v = first; v <= max + 1e-9; v += step) {
    out.push(Number(v.toFixed(10)));
  }
  return out;
}

// ── Chart geometry ────────────────────────────────────────────────────

const CHART_W = 1000;
const CHART_H = 380;
const VOL_H = 140;
const PAD_L = 10;
const PAD_R = 62;
const PAD_T = 12;
const PAD_B = 24;
const INNER_W = CHART_W - PAD_L - PAD_R;
const INNER_CH = CHART_H - PAD_T - PAD_B;
const INNER_VH = VOL_H - PAD_T - PAD_B;

type ViewState = {
  start: number;
  count: number;
  yMode: "auto" | "manual";
  yCenter: number;
  yRange: number;
};

function defaultView(nBars: number): ViewState {
  const count = Math.max(10, Math.min(nBars, 80));
  return {
    start: Math.max(0, nBars - count),
    count,
    yMode: "auto",
    yCenter: 0,
    yRange: 0,
  };
}

// ── Candle chart ──────────────────────────────────────────────────────

type ViewDerived = {
  start: number;
  count: number;
  visible: Bar[];
  yMin: number;
  yMax: number;
};

function deriveView(bars: Bar[], view: ViewState): ViewDerived {
  const n = bars.length;
  const start = Math.max(0, Math.min(Math.max(0, n - 1), Math.floor(view.start)));
  const count = Math.max(5, Math.min(n - start, Math.floor(view.count) || 1));
  const visible = bars.slice(start, start + count);
  let yMin: number;
  let yMax: number;
  if (view.yMode === "auto") {
    let lo = Infinity;
    let hi = -Infinity;
    for (const b of visible) {
      if (b.l < lo) lo = b.l;
      if (b.h > hi) hi = b.h;
    }
    if (!Number.isFinite(lo) || !Number.isFinite(hi)) {
      lo = 0;
      hi = 1;
    }
    const pad = (hi - lo) * 0.06 || Math.abs(hi) * 0.01 || 1;
    yMin = lo - pad;
    yMax = hi + pad;
  } else {
    yMin = view.yCenter - view.yRange / 2;
    yMax = view.yCenter + view.yRange / 2;
  }
  return { start, count, visible, yMin, yMax };
}

type DragState = {
  kind: "pan" | "scaleY";
  clientX: number;
  clientY: number;
  view: ViewState;
  yMin0: number;
  yMax0: number;
  svgW: number;
};

function CandleChart({
  bars,
  view,
  setView,
  barSize,
  interactive,
}: {
  bars: Bar[];
  view: ViewState;
  setView: (v: ViewState) => void;
  barSize: string;
  interactive: boolean;
}) {
  const theme = useHostTheme();
  const svgRef = useRef<SVGSVGElement | null>(null);
  const dragRef = useRef<DragState | null>(null);
  const [hoverIdx, setHoverIdx] = useState<number | null>(null);

  const { start, count, visible, yMin, yMax } = deriveView(bars, view);
  const xFor = (i: number) => PAD_L + (i + 0.5) * (INNER_W / count);
  const yFor = (p: number) =>
    PAD_T + ((yMax - p) / (yMax - yMin || 1)) * INNER_CH;
  const bw = Math.max(1.5, (INNER_W / count) * 0.72);

  const toSvg = useCallback((clientX: number, clientY: number) => {
    const svg = svgRef.current;
    if (!svg) return { x: 0, y: 0, width: 1 };
    const r = svg.getBoundingClientRect();
    return {
      x: ((clientX - r.left) / r.width) * CHART_W,
      y: ((clientY - r.top) / r.height) * CHART_H,
      width: r.width,
    };
  }, []);

  const handleWheel = useCallback(
    (e: WheelEvent) => {
      if (!interactive) return;
      const svg = svgRef.current;
      if (!svg) return;
      const r = svg.getBoundingClientRect();
      if (
        e.clientX < r.left ||
        e.clientX > r.right ||
        e.clientY < r.top ||
        e.clientY > r.bottom
      ) {
        return;
      }
      e.preventDefault();
      const sx = ((e.clientX - r.left) / r.width) * CHART_W;
      const onYAxis = sx > PAD_L + INNER_W;
      const d = deriveView(bars, view);
      if (onYAxis) {
        const range = d.yMax - d.yMin;
        const factor = e.deltaY > 0 ? 1.12 : 1 / 1.12;
        const center = (d.yMax + d.yMin) / 2;
        setView({
          ...view,
          yMode: "manual",
          yCenter: center,
          yRange: Math.max(1e-6, range * factor),
        });
      } else {
        const relX = Math.max(0, Math.min(1, (sx - PAD_L) / INNER_W));
        const anchor = d.start + relX * d.count;
        const factor = e.deltaY > 0 ? 1.25 : 1 / 1.25;
        const newCount = Math.max(
          5,
          Math.min(bars.length, Math.round(d.count * factor))
        );
        const newStart = Math.max(
          0,
          Math.min(
            bars.length - newCount,
            Math.round(anchor - relX * newCount)
          )
        );
        setView({ ...view, start: newStart, count: newCount });
      }
    },
    [bars, view, setView, interactive]
  );

  // Attach wheel only when chart interactions are enabled. When disabled,
  // normal canvas/page scrolling must win.
  useEffect(() => {
    if (!interactive) return;
    const svg = svgRef.current;
    if (!svg) return;
    svg.addEventListener("wheel", handleWheel, { passive: false });
    return () => svg.removeEventListener("wheel", handleWheel);
  }, [handleWheel, interactive]);

  const onMouseDown = (e: React.MouseEvent<SVGSVGElement>) => {
    if (!interactive) return;
    const { x, width } = toSvg(e.clientX, e.clientY);
    const onYAxis = x > PAD_L + INNER_W;
    const d = deriveView(bars, view);
    dragRef.current = {
      kind: onYAxis ? "scaleY" : "pan",
      clientX: e.clientX,
      clientY: e.clientY,
      view,
      yMin0: d.yMin,
      yMax0: d.yMax,
      svgW: width,
    };
    e.preventDefault();
  };

  useEffect(() => {
    const onMove = (e: MouseEvent) => {
      const d = dragRef.current;
      if (!d) return;
      if (d.kind === "pan") {
        const dx = ((e.clientX - d.clientX) / d.svgW) * CHART_W;
        const barPix = INNER_W / d.view.count;
        const dIdx = -Math.round(dx / barPix);
        const newStart = Math.max(
          0,
          Math.min(bars.length - d.view.count, d.view.start + dIdx)
        );
        setView({ ...d.view, start: newStart });
      } else {
        const dy = e.clientY - d.clientY;
        const factor = Math.pow(1.006, dy);
        const range0 = d.yMax0 - d.yMin0;
        const center0 = (d.yMax0 + d.yMin0) / 2;
        setView({
          ...d.view,
          yMode: "manual",
          yCenter: center0,
          yRange: Math.max(1e-6, range0 * factor),
        });
      }
    };
    const onUp = () => {
      dragRef.current = null;
    };
    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onUp);
    return () => {
      window.removeEventListener("mousemove", onMove);
      window.removeEventListener("mouseup", onUp);
    };
  }, [bars.length, setView]);

  const onMouseMoveChart = (e: React.MouseEvent<SVGSVGElement>) => {
    const { x, y } = toSvg(e.clientX, e.clientY);
    if (
      x < PAD_L ||
      x > PAD_L + INNER_W ||
      y < PAD_T ||
      y > PAD_T + INNER_CH
    ) {
      setHoverIdx(null);
      return;
    }
    const relX = (x - PAD_L) / INNER_W;
    const i = Math.max(0, Math.min(count - 1, Math.floor(relX * count)));
    setHoverIdx(i);
  };

  const onMouseLeave = () => setHoverIdx(null);

  const yTicks = useMemo(() => niceTicks(yMin, yMax, 6), [yMin, yMax]);
  const xTickEvery = Math.max(1, Math.round(count / 8));
  const xLabels: { i: number; label: string }[] = [];
  for (let i = 0; i < visible.length; i += xTickEvery) {
    xLabels.push({ i, label: shortLabel(visible[i].t, barSize) });
  }

  const gridColor = theme.stroke.tertiary;
  const axisColor = theme.stroke.secondary;
  const labelColor = theme.text.tertiary;
  const upColor = theme.diff.stripAdded;
  const downColor = theme.diff.stripRemoved;
  const crosshairColor = theme.text.quaternary;

  const hoverBar = hoverIdx !== null ? visible[hoverIdx] : null;

  return (
    <div style={{ position: "relative", width: "100%" }}>
      <svg
        ref={svgRef}
        viewBox={`0 0 ${CHART_W} ${CHART_H}`}
        preserveAspectRatio="none"
        style={{
          width: "100%",
          height: CHART_H,
          display: "block",
          cursor: interactive
            ? dragRef.current?.kind === "pan"
              ? "grabbing"
              : "crosshair"
            : "default",
          userSelect: "none",
          touchAction: interactive ? "none" : "auto",
        }}
        onMouseDown={interactive ? onMouseDown : undefined}
        onMouseMove={onMouseMoveChart}
        onMouseLeave={onMouseLeave}
      >
        <rect
          x={PAD_L}
          y={PAD_T}
          width={INNER_W}
          height={INNER_CH}
          fill={theme.bg.editor}
          stroke={axisColor}
        />

        {yTicks.map((t) => {
          const y = yFor(t);
          return (
            <g key={`y-${t}`}>
              <line
                x1={PAD_L}
                x2={PAD_L + INNER_W}
                y1={y}
                y2={y}
                stroke={gridColor}
                strokeWidth={1}
              />
              <text
                x={PAD_L + INNER_W + 6}
                y={y + 3}
                fill={labelColor}
                fontSize={10}
                fontFamily="ui-monospace, SFMono-Regular, Menlo, monospace"
              >
                {formatPrice(t)}
              </text>
            </g>
          );
        })}

        {xLabels.map(({ i, label }) => {
          const x = xFor(i);
          return (
            <g key={`x-${i}`}>
              <line
                x1={x}
                x2={x}
                y1={PAD_T}
                y2={PAD_T + INNER_CH}
                stroke={gridColor}
                strokeWidth={1}
              />
              <text
                x={x}
                y={PAD_T + INNER_CH + 14}
                fill={labelColor}
                fontSize={10}
                fontFamily="ui-monospace, SFMono-Regular, Menlo, monospace"
                textAnchor="middle"
              >
                {label}
              </text>
            </g>
          );
        })}

        {visible.map((b, i) => {
          const up = b.c >= b.o;
          const color = up ? upColor : downColor;
          const x = xFor(i);
          const yO = yFor(b.o);
          const yC = yFor(b.c);
          const yH = yFor(b.h);
          const yL = yFor(b.l);
          const bodyTop = Math.min(yO, yC);
          const bodyH = Math.max(1, Math.abs(yC - yO));
          return (
            <g key={`c-${start + i}`}>
              <line
                x1={x}
                x2={x}
                y1={yH}
                y2={yL}
                stroke={color}
                strokeWidth={1}
              />
              <rect
                x={x - bw / 2}
                y={bodyTop}
                width={bw}
                height={bodyH}
                fill={up ? color : color}
                stroke={color}
                strokeWidth={1}
                opacity={up ? 0.95 : 0.95}
              />
            </g>
          );
        })}

        {hoverIdx !== null && hoverBar && (
          <g>
            <line
              x1={xFor(hoverIdx)}
              x2={xFor(hoverIdx)}
              y1={PAD_T}
              y2={PAD_T + INNER_CH}
              stroke={crosshairColor}
              strokeWidth={1}
              strokeDasharray="3 3"
            />
          </g>
        )}

        <rect
          x={PAD_L + INNER_W}
          y={PAD_T}
          width={PAD_R - 2}
          height={INNER_CH}
          fill="transparent"
          style={{ cursor: "ns-resize" }}
        />
      </svg>

      {hoverBar && (
        <div
          style={{
            position: "absolute",
            top: 8,
            left: 16,
            padding: "6px 10px",
            borderRadius: 6,
            background: theme.bg.elevated,
            border: `1px solid ${theme.stroke.secondary}`,
            fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
            fontSize: 11,
            color: theme.text.primary,
            pointerEvents: "none",
            lineHeight: 1.45,
          }}
        >
          <div style={{ color: theme.text.secondary, marginBottom: 2 }}>
            {shortLabel(hoverBar.t, barSize)}
          </div>
          <div>
            O {formatPrice(hoverBar.o)} · H {formatPrice(hoverBar.h)}
          </div>
          <div>
            L {formatPrice(hoverBar.l)} · C {formatPrice(hoverBar.c)}
          </div>
          <div style={{ color: theme.text.secondary }}>
            V {formatVolume(hoverBar.v)}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Volume chart (aligned x-axis with candle chart) ───────────────────

function VolumeChart({
  bars,
  view,
  barSize,
}: {
  bars: Bar[];
  view: ViewState;
  barSize: string;
}) {
  const theme = useHostTheme();
  const { start, count, visible } = deriveView(bars, view);
  const vMax = visible.reduce((m, b) => Math.max(m, b.v), 0) || 1;
  const xFor = (i: number) => PAD_L + (i + 0.5) * (INNER_W / count);
  const yFor = (v: number) => PAD_T + (1 - v / vMax) * INNER_VH;
  const bw = Math.max(1.2, (INNER_W / count) * 0.72);

  const upColor = theme.diff.stripAdded;
  const downColor = theme.diff.stripRemoved;
  const axisColor = theme.stroke.secondary;
  const labelColor = theme.text.tertiary;
  const gridColor = theme.stroke.tertiary;

  const vTicks = useMemo(() => niceTicks(0, vMax, 3), [vMax]);

  return (
    <svg
      viewBox={`0 0 ${CHART_W} ${VOL_H}`}
      preserveAspectRatio="none"
      style={{ width: "100%", height: VOL_H, display: "block" }}
    >
      <rect
        x={PAD_L}
        y={PAD_T}
        width={INNER_W}
        height={INNER_VH}
        fill={theme.bg.editor}
        stroke={axisColor}
      />

      {vTicks.map((t) => {
        const y = yFor(t);
        return (
          <g key={`v-${t}`}>
            <line
              x1={PAD_L}
              x2={PAD_L + INNER_W}
              y1={y}
              y2={y}
              stroke={gridColor}
            />
            <text
              x={PAD_L + INNER_W + 6}
              y={y + 3}
              fill={labelColor}
              fontSize={10}
              fontFamily="ui-monospace, SFMono-Regular, Menlo, monospace"
            >
              {formatVolume(t)}
            </text>
          </g>
        );
      })}

      {visible.map((b, i) => {
        const up = b.c >= b.o;
        const x = xFor(i);
        const y = yFor(b.v);
        const h = Math.max(1, PAD_T + INNER_VH - y);
        return (
          <rect
            key={`vbar-${start + i}`}
            x={x - bw / 2}
            y={y}
            width={bw}
            height={h}
            fill={up ? upColor : downColor}
            opacity={0.85}
          />
        );
      })}
    </svg>
  );
}

// ── Canvas ────────────────────────────────────────────────────────────

export default function VolbookFuturesOhlcv() {
  const contractOptions = useMemo(
    () =>
      uniqueOrdered(BUNDLE.map((s) => s.contract_key)).map((ck) => {
        const label =
          BUNDLE.find((s) => s.contract_key === ck)?.contract_label ?? ck;
        return { value: ck, label };
      }),
    []
  );

  const [contract, setContract] = useCanvasState<string>(
    "volbook.contract",
    contractOptions[0]?.value ?? ""
  );

  const timeframeOptions = useMemo(
    () =>
      uniqueOrdered(
        BUNDLE.filter((s) => s.contract_key === contract).map((s) => s.bar_size)
      ).map((bs) => ({ value: bs, label: bs })),
    [contract]
  );

  const [timeframe, setTimeframe] = useCanvasState<string>(
    "volbook.timeframe",
    timeframeOptions[0]?.value ?? ""
  );
  const [showVolume, setShowVolume] = useCanvasState<boolean>(
    "volbook.showVol",
    true
  );
  const [chartInteractive, setChartInteractive] = useCanvasState<boolean>(
    "volbook.chartInteractive",
    false
  );

  const resolvedTimeframe =
    timeframeOptions.find((o) => o.value === timeframe)?.value ??
    timeframeOptions[0]?.value ??
    "";

  const selected =
    BUNDLE.find(
      (s) => s.contract_key === contract && s.bar_size === resolvedTimeframe
    ) ?? BUNDLE[0];

  const seriesKey = selected ? selected.key : "empty";
  const [view, setView] = useCanvasState<ViewState>(
    `volbook.view.${seriesKey}`,
    defaultView(selected ? selected.bars.length : 0)
  );

  if (!selected) {
    return (
      <Stack gap={20}>
        <H1>Volatility Book — Futures OHLCV</H1>
        <Text tone="secondary">
          No series available. Run{" "}
          <Text as="span" weight="semibold">
            python -m scripts.volbook.fetch_futures_ohlcv
          </Text>{" "}
          to pull bars from IB.
        </Text>
      </Stack>
    );
  }

  const bars = selected.bars;
  const first = bars[0];
  const last = bars[bars.length - 1];
  const periodOpen = first ? first.o : NaN;
  const periodChange = first && last ? last.c / first.c - 1 : NaN;
  const periodHigh = bars.reduce((m, b) => Math.max(m, b.h), -Infinity);
  const periodLow = bars.reduce((m, b) => Math.min(m, b.l), Infinity);
  const rv20 = realizedVol(bars, 20, selected.bar_size);
  const indicatorCategoryCount = Object.keys(selected.indicators || {}).length;
  const indicatorCount = Object.values(selected.indicators || {}).reduce(
    (acc, rows) => acc + rows.length,
    0
  );
  const setupCount = (selected.setups || []).length;

  const tailCount = Math.min(12, bars.length);
  const tail = bars.slice(bars.length - tailCount);
  const tableRows = tail
    .slice()
    .reverse()
    .map((b) => [
      shortLabel(b.t, selected.bar_size),
      formatPrice(b.o),
      formatPrice(b.h),
      formatPrice(b.l),
      formatPrice(b.c),
      formatVolume(b.v),
    ]);

  const resetView = () => setView(defaultView(bars.length));
  const zoomIn = () =>
    setView({
      ...view,
      count: Math.max(5, Math.round(view.count / 1.25)),
      start: Math.min(
        bars.length - Math.max(5, Math.round(view.count / 1.25)),
        view.start +
          Math.round((view.count - Math.max(5, Math.round(view.count / 1.25))) / 2)
      ),
    });
  const zoomOut = () => {
    const newCount = Math.min(bars.length, Math.round(view.count * 1.25));
    const delta = newCount - view.count;
    setView({
      ...view,
      count: newCount,
      start: Math.max(0, Math.min(bars.length - newCount, view.start - Math.round(delta / 2))),
    });
  };

  return (
    <Stack gap={20}>
      <Row gap={12} align="center" justify="space-between" wrap>
        <Stack gap={4}>
          <H1>Volatility Book — Futures OHLCV</H1>
          <Text tone="secondary" size="small">
            {selected.contract_label} · {selected.exchange} ·{" "}
            {selected.bar_size} · {bars.length} bars · data as of{" "}
            {selected.fetched_at || GENERATED_AT}
          </Text>
        </Stack>
        <Row gap={8} align="center" wrap>
          <Pill tone="info" size="sm">
            {selected.what_to_show}
          </Pill>
          <Pill tone={indicatorCount > 0 ? "success" : "warning"} size="sm">
            TA-Lib {indicatorCount} indicators / {indicatorCategoryCount} groups
          </Pill>
          <Pill tone={setupCount > 0 ? "info" : "neutral"} size="sm">
            {setupCount} risk/reward setup{setupCount === 1 ? "" : "s"}
          </Pill>
        </Row>
      </Row>

      <Row gap={16} align="center" wrap>
        <Stack gap={4} style={{ minWidth: 220 }}>
          <Text size="small" tone="secondary">
            Contract
          </Text>
          <Select
            value={contract}
            onChange={setContract}
            options={contractOptions}
          />
        </Stack>
        <Stack gap={4} style={{ minWidth: 160 }}>
          <Text size="small" tone="secondary">
            Timeframe
          </Text>
          <Select
            value={resolvedTimeframe}
            onChange={setTimeframe}
            options={timeframeOptions}
          />
        </Stack>
        <Row gap={8} align="center">
          <Text size="small">Volume</Text>
          <Toggle checked={showVolume} onChange={setShowVolume} />
        </Row>
        <Row gap={8} align="center">
          <Text size="small">Chart drag/zoom</Text>
          <Toggle checked={chartInteractive} onChange={setChartInteractive} />
        </Row>
        <Row gap={8} align="center">
          <Button variant="ghost" onClick={zoomOut}>
            −
          </Button>
          <Button variant="ghost" onClick={zoomIn}>
            +
          </Button>
          <Button variant="secondary" onClick={resetView}>
            Reset view
          </Button>
        </Row>
      </Row>

      <Grid columns={6} gap={16}>
        <Stat value={formatPrice(last.c)} label="Last" />
        <Stat
          value={formatPct(periodChange)}
          label="Period change"
          tone={periodChange >= 0 ? "success" : "danger"}
        />
        <Stat value={formatPrice(periodOpen)} label="Period open" />
        <Stat value={formatPrice(periodHigh)} label="Period high" />
        <Stat value={formatPrice(periodLow)} label="Period low" />
        <Stat
          value={Number.isFinite(rv20) ? formatPct(rv20) : "—"}
          label="Realized vol (20-bar)"
          tone="info"
        />
      </Grid>

      <Divider />

      <Row gap={12} align="center" justify="space-between">
        <H2>Price (candlesticks)</H2>
        <Text tone="tertiary" size="small">
          Chart drag/zoom is off by default so the canvas scrolls normally.
          Enable it above for pan/zoom and movable Y scale.
        </Text>
      </Row>
      <CandleChart
        bars={bars}
        view={view}
        setView={setView}
        barSize={selected.bar_size}
        interactive={chartInteractive}
      />

      {showVolume && (
        <>
          <H2>Volume</H2>
          <VolumeChart bars={bars} view={view} barSize={selected.bar_size} />
        </>
      )}

      <Divider />

      <BestSetups series={selected} />

      <Divider />

      <IndicatorsSection series={selected} />

      <Divider />

      <H2>Recent bars</H2>
      <Table
        headers={["Date", "Open", "High", "Low", "Close", "Volume"]}
        rows={tableRows}
        columnAlign={["left", "right", "right", "right", "right", "right"]}
        striped
      />
    </Stack>
  );
}

// ── Best risk:reward setups ──────────────────────────────────────────

function formatMoney(x: number): string {
  if (!Number.isFinite(x)) return "—";
  const abs = Math.abs(x);
  if (abs >= 1000) return x.toFixed(2);
  if (abs >= 1) return x.toFixed(4);
  return x.toFixed(6);
}

function BestSetups({ series }: { series: Series }) {
  const setups = series.setups || [];

  if (setups.length === 0) {
    return (
      <Stack gap={8}>
        <H2>Best technical risk:reward</H2>
        <Text tone="secondary">
          No actionable trend, mean-reversion, or breakout setups fired on
          the latest bar. This is expected in choppy / transitional regimes;
          the indicator tables below still show every TA-Lib reading.
        </Text>
      </Stack>
    );
  }

  const best = setups[0];
  const last = series.bars[series.bars.length - 1];
  const lastClose = last ? last.c : best.entry;

  return (
    <Stack gap={12}>
      <Row gap={12} align="center" justify="space-between" wrap>
        <Stack gap={4}>
          <H2>Best technical risk:reward</H2>
          <Text size="small" tone="secondary">
            Ranked by RR × confidence. Entry at last close ({formatPrice(lastClose)}),
            stops and targets anchored to ATR/Bollinger/range levels. Top {setups.length}
            {setups.length === 1 ? " setup" : " setups"} shown.
          </Text>
        </Stack>
        <Pill
          tone={best.direction === "long" ? "success" : "deleted"}
          size="md"
        >
          Best: {best.direction.toUpperCase()} · RR {best.rr.toFixed(2)} · conf {(best.confidence * 100).toFixed(0)}%
        </Pill>
      </Row>

      <Grid columns={Math.min(setups.length, 2)} gap={12}>
        {setups.map((s, i) => {
          const isLong = s.direction === "long";
          const tone: "success" | "danger" = isLong ? "success" : "danger";
          const pillTone: "success" | "deleted" = isLong ? "success" : "deleted";
          const rrPillTone =
            s.rr >= 2.5 ? "success" : s.rr >= 1.5 ? "info" : "neutral";
          return (
            <Card key={`${s.name}-${s.direction}-${i}`}>
              <CardHeader
                trailing={
                  <Pill tone={rrPillTone} size="sm">
                    RR {s.rr.toFixed(2)}
                  </Pill>
                }
              >
                {i === 0 ? "#1 " : ""}
                {s.name} · {s.direction.toUpperCase()}
              </CardHeader>
              <CardBody>
                <Stack gap={12}>
                  <Grid columns={4} gap={8}>
                    <Stat label="Entry" value={formatPrice(s.entry)} />
                    <Stat
                      label="Stop"
                      value={formatPrice(s.stop)}
                      tone="danger"
                    />
                    <Stat
                      label="Target"
                      value={formatPrice(s.target)}
                      tone={tone}
                    />
                    <Stat
                      label="Confidence"
                      value={`${(s.confidence * 100).toFixed(0)}%`}
                    />
                  </Grid>
                  <Row gap={12} wrap>
                    <Pill tone={pillTone} size="sm">
                      {isLong ? "Long" : "Short"}
                    </Pill>
                    {s.tags.map((t) => (
                      <Pill key={t} size="sm" tone="neutral">
                        {t}
                      </Pill>
                    ))}
                    <Text size="small" tone="secondary">
                      Risk {formatMoney(s.risk)} · Reward {formatMoney(s.reward)}
                    </Text>
                  </Row>
                  <Stack gap={4}>
                    {s.rationale.map((line, j) => (
                      <Text key={j} size="small" tone="primary">
                        · {line}
                      </Text>
                    ))}
                  </Stack>
                </Stack>
              </CardBody>
            </Card>
          );
        })}
      </Grid>
    </Stack>
  );
}

// ── Indicators section ────────────────────────────────────────────────

function formatIndicatorNum(x: number | null): string {
  if (x === null || !Number.isFinite(x)) return "—";
  const abs = Math.abs(x);
  if (abs >= 1e6) return x.toExponential(2);
  if (abs >= 1000) return x.toFixed(2);
  if (abs >= 1) return x.toFixed(4);
  return x.toFixed(6);
}

function formatParams(params: Record<string, number | string>): string {
  const entries = Object.entries(params);
  if (entries.length === 0) return "—";
  return entries.map(([k, v]) => `${k}=${v}`).join(", ");
}

function formatChange(curr: number | null, prev: number | null): string {
  if (curr === null || prev === null) return "—";
  const d = curr - prev;
  if (!Number.isFinite(d)) return "—";
  const sign = d > 0 ? "+" : "";
  return `${sign}${formatIndicatorNum(d)}`;
}

function patternToneLabel(v: number | null): {
  label: string;
  tone: "success" | "danger" | "neutral";
} {
  if (v === null || v === 0) return { label: "—", tone: "neutral" };
  if (v > 0) return { label: `Bullish (${v})`, tone: "success" };
  return { label: `Bearish (${v})`, tone: "danger" };
}

function IndicatorsSection({ series }: { series: Series }) {
  const theme = useHostTheme();
  const indicators = series.indicators || {};
  const categoryNames = Object.keys(indicators);

  const [query, setQuery] = useCanvasState<string>("volbook.ind.query", "");
  const [hideFlat, setHideFlat] = useCanvasState<boolean>(
    "volbook.ind.hideFlat",
    false
  );

  if (categoryNames.length === 0) {
    return (
      <Stack gap={12}>
        <H2>Technical indicators</H2>
        <Text tone="secondary">
          No indicators attached. Rerun the CLI without{" "}
          <Text as="span" weight="semibold">
            --no-indicators
          </Text>{" "}
          (requires TA-Lib: <Text as="span" weight="semibold">pip install -e .[ta]</Text>).
        </Text>
      </Stack>
    );
  }

  const totalRows = categoryNames.reduce(
    (acc, c) => acc + indicators[c].length,
    0
  );

  const patternRows = indicators["Pattern Recognition"] ?? [];
  const nonPatternCategories = categoryNames.filter(
    (c) => c !== "Pattern Recognition"
  );

  const needle = query.trim().toLowerCase();
  const matches = (r: IndicatorRecord) =>
    !needle ||
    r.function.toLowerCase().includes(needle) ||
    r.display_name.toLowerCase().includes(needle);

  // Collect recent pattern firings (non-zero signals in the stored tail).
  type PatternFire = {
    function: string;
    display_name: string;
    offset: number;
    value: number;
  };
  const patternFires: PatternFire[] = [];
  for (const rec of patternRows) {
    const arr = rec.outputs.integer ?? [];
    for (let j = arr.length - 1; j >= 0; j--) {
      const v = arr[j];
      if (v !== null && v !== 0 && Number.isFinite(v)) {
        patternFires.push({
          function: rec.function,
          display_name: rec.display_name,
          offset: arr.length - 1 - j,
          value: v,
        });
      }
    }
  }
  patternFires.sort((a, b) => a.offset - b.offset || a.function.localeCompare(b.function));

  return (
    <Stack gap={16}>
      <Row gap={12} align="center" justify="space-between" wrap>
        <Stack gap={4}>
          <H2>Technical indicators</H2>
          <Text size="small" tone="secondary">
            {totalRows} TA-Lib indicators across {categoryNames.length}{" "}
            categories · values computed on every bar; tables show the most
            recent snapshot
          </Text>
        </Stack>
        <Row gap={10} align="center">
          <Row gap={6} align="center">
            <Text size="small" tone="secondary">
              Filter
            </Text>
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="e.g. RSI, MACD, ATR"
              style={{
                width: 160,
                height: 24,
                padding: "0 8px",
                borderRadius: 4,
                border: `1px solid ${theme.stroke.primary}`,
                background: theme.bg.editor,
                color: theme.text.primary,
                fontSize: 12,
                fontFamily: "inherit",
                outline: "none",
              }}
            />
          </Row>
          <Row gap={6} align="center">
            <Text size="small" tone="secondary">
              Hide flat
            </Text>
            <Toggle checked={hideFlat} onChange={setHideFlat} />
          </Row>
        </Row>
      </Row>

      {/* Pattern Recognition — recent firings summary (always on top). */}
      {patternRows.length > 0 && (
        <Card collapsible defaultOpen>
          <CardHeader
            trailing={
              <Pill tone={patternFires.length > 0 ? "info" : "neutral"} size="sm">
                {patternFires.length} recent
              </Pill>
            }
          >
            Pattern Recognition — recent firings
          </CardHeader>
          <CardBody>
            {patternFires.length === 0 ? (
              <Text tone="secondary">
                No candlestick patterns fired in the last{" "}
                {patternRows[0]?.outputs?.integer?.length ?? 0} bars.
              </Text>
            ) : (
              <Table
                headers={["Bars ago", "Pattern", "Function", "Signal"]}
                rows={patternFires.map((p) => {
                  const tl = patternToneLabel(p.value);
                  return [
                    p.offset === 0 ? "now" : `${p.offset}`,
                    p.display_name,
                    p.function,
                    tl.label,
                  ];
                })}
                rowTone={patternFires.map((p) =>
                  p.value > 0 ? "success" : p.value < 0 ? "danger" : undefined
                )}
                columnAlign={["right", "left", "left", "left"]}
                striped
                stickyHeader
              />
            )}
          </CardBody>
        </Card>
      )}

      {/* One collapsible card per non-pattern category. */}
      {nonPatternCategories.map((cat) => {
        const rows = indicators[cat].filter(matches);
        const tableRows = rows
          .filter((r) => {
            if (!hideFlat) return true;
            // flat = every output is null/NaN or an all-zero signal
            const vals = Object.values(r.outputs);
            if (vals.length === 0) return false;
            return vals.some((arr) => {
              const latest = arr.length > 0 ? arr[arr.length - 1] : null;
              return latest !== null && latest !== 0;
            });
          })
          .flatMap((r) => {
            const outNames = Object.keys(r.outputs);
            if (outNames.length === 0) {
              return [
                [
                  r.function,
                  formatParams(r.params),
                  "—",
                  r.error ? `error: ${r.error}` : "—",
                  "—",
                  "—",
                ],
              ];
            }
            return outNames.map((outName, idx) => {
              const arr = r.outputs[outName] ?? [];
              const curr = arr.length > 0 ? arr[arr.length - 1] : null;
              const prev = arr.length > 1 ? arr[arr.length - 2] : null;
              return [
                idx === 0 ? r.function : "",
                idx === 0 ? formatParams(r.params) : "",
                outName,
                formatIndicatorNum(curr),
                formatIndicatorNum(prev),
                formatChange(curr, prev),
              ];
            });
          });

        return (
          <Card key={cat} collapsible defaultOpen={false}>
            <CardHeader
              trailing={
                <Pill size="sm" tone="neutral">
                  {indicators[cat].length}
                </Pill>
              }
            >
              {cat}
            </CardHeader>
            <CardBody>
              {tableRows.length === 0 ? (
                <Text tone="secondary">
                  No indicators match the current filter.
                </Text>
              ) : (
                <Table
                  headers={[
                    "Function",
                    "Params",
                    "Output",
                    "Latest",
                    "Prev",
                    "Change",
                  ]}
                  rows={tableRows}
                  columnAlign={[
                    "left",
                    "left",
                    "left",
                    "right",
                    "right",
                    "right",
                  ]}
                  striped
                  stickyHeader
                />
              )}
            </CardBody>
          </Card>
        );
      })}
    </Stack>
  );
}
'''


def _series_for_canvas(bundle: OhlcvBundle) -> list[dict]:
    """Produce the JSON-ready list the canvas expects in ``BUNDLE``."""
    out: list[dict] = []
    for s in bundle.series:
        spec = FuturesSpec(
            symbol=s.symbol, exchange=s.exchange, expiry=s.expiry, currency=s.currency
        )
        out.append(
            {
                "key": s.key,
                "contract_key": s.contract_key,
                "contract_label": spec.label,
                "symbol": s.symbol,
                "expiry": s.expiry,
                "exchange": s.exchange,
                "bar_size": s.bar_size,
                "duration": s.duration,
                "what_to_show": s.what_to_show,
                "fetched_at": s.fetched_at,
                "bars": [
                    {"t": b.t, "o": b.o, "h": b.h, "l": b.l, "c": b.c, "v": b.v}
                    for b in s.bars
                ],
                "indicators": s.indicators or {},
                "setups": s.setups or [],
            }
        )
    return out


def render_canvas(bundle: OhlcvBundle) -> str:
    """Render the TSX body for the canvas as a string."""
    payload = _series_for_canvas(bundle)
    bundle_json = json.dumps(payload, ensure_ascii=False, separators=(", ", ": "))
    return _TEMPLATE.replace("__BUNDLE_JSON__", bundle_json).replace(
        "__GENERATED_AT__", bundle.generated_at or ""
    )


def write_canvas(bundle: OhlcvBundle, path: str | Path) -> Path:
    """Render + write the canvas file. Creates parents as needed."""
    p = Path(os.path.expanduser(str(path)))
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_canvas(bundle))
    return p


def default_canvas_path() -> Path:
    """Workspace-specific canvas directory expected by the Cursor IDE."""
    return (
        Path.home()
        / ".cursor"
        / "projects"
        / "Users-russellfloyd-Dropbox-NRT-nrt-dev-trend-crypto"
        / "canvases"
        / "volbook-futures-ohlcv.canvas.tsx"
    )
