"""Exploratory CL signal-research report and graphics.

The outputs in this module are diagnostics only. They summarize probabilistic
1d volatility-expansion research by regime and validation fold; they do not
define entries, exits, sizing, or portfolio construction.
"""
from __future__ import annotations

import hashlib
import importlib.metadata
import json
import platform
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from k2_systematic_macro.configs.cl import CLResearchConfig
from k2_systematic_macro.csv_export import write_research_csv
from k2_systematic_macro.data.dataset import ResearchDataset
from k2_systematic_macro.models.expansion import ExpansionModelResult
from k2_systematic_macro.regimes.evaluation import RegimeEvaluation
from k2_systematic_macro.signals.trade_candidates import build_trade_candidate_artifacts
from volbook.continuous import (
    NymexObservedHolidayCalendar,
    RollPolicy,
    WeekendHolidayCalendar,
    construct_continuous_series,
)
from volbook.datalake import CONTINUOUS_EXPIRY, MinuteLake


CONVEXITY_RESEARCH_SCORE_DEFINITION = (
    "convexity_research_score = event_rate + mean_probability + tail_participation "
    "- abs(drawdown_proxy), where null tail_participation and drawdown_proxy are treated as 0. "
    "It is a reproducible diagnostic ranking score only, not an expected-return or trading score."
)


@dataclass(frozen=True)
class SignalResearchArtifacts:
    """Files generated by the signal-research report layer."""

    paths: dict[str, Path]
    summary: dict[str, Any]


@dataclass(frozen=True)
class TopCellSelectorConfig:
    """Deterministic selector for highlighted regime/probability-decile cells."""

    min_n: int = 30
    sort_key: tuple[str, ...] = (
        "event_rate",
        "mean_probability",
        "convexity_research_score",
        "n",
        "regime",
        "probability_decile",
    )
    ascending: tuple[bool, ...] = (False, False, False, False, True, False)


@dataclass(frozen=True)
class DiagnosticsThresholdConfig:
    """Assertion-style diagnostic thresholds for report health, not strategy quality."""

    calibration_monotonic_share_min: float = 0.50
    calibration_spearman_median_min: float = 0.0
    top_cell_min_n: int = 30
    smoke_auc_edge_max_abs: float = 0.10
    smoke_probability_label_corr_max_abs: float = 0.10
    smoke_seed: int = 42


def build_signal_research_artifacts(
    *,
    output_dir: Path,
    dataset: ResearchDataset,
    cl_config: CLResearchConfig,
    primary_timeframe: str,
    primary_panel: pd.DataFrame,
    regime_eval: RegimeEvaluation,
    expansion_results: dict[str, ExpansionModelResult],
    run_config: dict[str, Any] | None = None,
    top_cell_selector: TopCellSelectorConfig | None = None,
    thresholds: DiagnosticsThresholdConfig | None = None,
) -> SignalResearchArtifacts:
    """Write markdown, CSV, and PNG artifacts for points 1-5."""

    selector = top_cell_selector or TopCellSelectorConfig()
    threshold_cfg = thresholds or DiagnosticsThresholdConfig()
    graphics_dir = output_dir / "graphics"
    graphics_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}

    target_coverage = _target_coverage(primary_panel)
    paths["target_coverage"] = _write_frame(target_coverage, output_dir / "target_coverage.csv")
    target_missing_rows = _target_missing_reason_rows(primary_panel, dataset, primary_timeframe)
    target_missing_reasons = _target_missing_reason_summary(target_missing_rows)
    paths["target_missing_rows"] = _write_frame(target_missing_rows, output_dir / "target_missing_rows.csv")
    paths["target_missing_reasons"] = _write_frame(
        target_missing_reasons,
        output_dir / "target_missing_reasons.csv",
    )
    paths["target_coverage_chart"] = _plot_target_coverage(
        target_coverage,
        graphics_dir / "target_coverage.png",
        dataset,
        primary_timeframe,
    )
    paths["target_missing_reasons_chart"] = _plot_target_missing_reasons(
        target_missing_reasons,
        graphics_dir / "target_missing_reasons.png",
        dataset,
    )

    roll_summary, roll_compare = _roll_sensitivity(cl_config)
    paths["roll_sensitivity_summary"] = _write_frame(roll_summary, output_dir / "roll_sensitivity_summary.csv")
    paths["roll_sensitivity_compare"] = _write_frame(roll_compare, output_dir / "roll_sensitivity_compare.csv")
    roll_assertions = _roll_sensitivity_assertions(roll_summary)
    paths["roll_sensitivity_assertions"] = _write_frame(
        roll_assertions,
        output_dir / "roll_sensitivity_assertions.csv",
    )
    paths["roll_sensitivity_chart"] = _plot_roll_sensitivity(
        roll_compare,
        graphics_dir / "roll_sensitivity.png",
        dataset,
    )

    model_kind, model_result = _preferred_model(expansion_results)
    joined = _prediction_panel(primary_panel, model_result.predictions if model_result else pd.DataFrame())
    regime_deciles = _regime_decile_diagnostics(joined)
    paths["regime_decile_diagnostics"] = _write_frame(
        regime_deciles,
        output_dir / "regime_decile_diagnostics.csv",
    )
    selected_cells = _select_top_cells(regime_deciles, selector)
    paths["selected_top_cells"] = _write_frame(selected_cells, output_dir / "selected_top_cells.csv")
    paths["regime_event_chart"] = _plot_regime_deciles(
        regime_deciles,
        graphics_dir / "regime_decile_event_rates.png",
        dataset,
        model_kind,
    )
    paths["conditional_return_chart"] = _plot_conditional_returns(
        joined,
        graphics_dir / "conditional_forward_returns.png",
        dataset,
        model_kind,
    )

    fold_diagnostics = _fold_diagnostics(model_result.predictions if model_result else pd.DataFrame())
    paths["fold_diagnostics"] = _write_frame(fold_diagnostics, output_dir / "fold_diagnostics.csv")
    calibration_summary = _calibration_summary(fold_diagnostics)
    paths["calibration_summary"] = _write_frame(calibration_summary, output_dir / "calibration_summary.csv")
    paths["fold_auc_chart"] = _plot_fold_auc(
        fold_diagnostics,
        graphics_dir / "fold_auc_diagnostics.png",
        dataset,
        model_kind,
    )
    calibration = model_result.calibration if model_result else pd.DataFrame()
    paths["calibration_chart"] = _plot_calibration(
        calibration,
        graphics_dir / "probability_calibration.png",
        dataset,
        model_kind,
    )
    paths["calibration_spearman_chart"] = _plot_calibration_spearman(
        fold_diagnostics,
        graphics_dir / "calibration_spearman_by_fold.png",
        dataset,
        model_kind,
    )

    smoke_null = _smoke_null_diagnostics(
        model_result.predictions if model_result else pd.DataFrame(),
        seed=threshold_cfg.smoke_seed,
    )
    paths["smoke_null_diagnostics"] = _write_frame(smoke_null, output_dir / "smoke_null_diagnostics.csv")
    paths["smoke_null_chart"] = _plot_smoke_null(
        smoke_null,
        graphics_dir / "smoke_null_diagnostics.png",
        dataset,
        model_kind,
    )

    overlay = _regime2_overlay(joined)
    paths["regime2_overlay"] = _write_frame(overlay, output_dir / "regime2_overlay_comparison.csv")
    paths["regime2_overlay_chart"] = _plot_regime2_overlay(
        overlay,
        graphics_dir / "regime2_overlay_comparison.png",
        dataset,
        model_kind,
    )

    diagnostics_harness = _diagnostics_harness(
        target_missing_reasons=target_missing_reasons,
        roll_assertions=roll_assertions,
        fold_diagnostics=fold_diagnostics,
        calibration_summary=calibration_summary,
        selected_cells=selected_cells,
        smoke_null=smoke_null,
        thresholds=threshold_cfg,
    )
    paths["diagnostics_harness"] = _write_frame(diagnostics_harness, output_dir / "diagnostics_harness.csv")
    paths["diagnostics_harness_chart"] = _plot_diagnostics_harness(
        diagnostics_harness,
        graphics_dir / "diagnostics_harness.png",
        dataset,
    )
    trade_candidate_artifacts = build_trade_candidate_artifacts(
        output_dir=output_dir,
        dataset=dataset,
        primary_panel=primary_panel,
        predictions=model_result.predictions if model_result else pd.DataFrame(),
        diagnostics_harness=diagnostics_harness,
        model_kind=model_kind,
    )
    paths.update(trade_candidate_artifacts.paths)
    manifest = _run_manifest(
        output_dir=output_dir,
        dataset=dataset,
        primary_timeframe=primary_timeframe,
        primary_panel=primary_panel,
        cl_config=cl_config,
        run_config=run_config or {},
        selector=selector,
        thresholds=threshold_cfg,
    )
    paths["run_manifest"] = _write_json(output_dir / "run_manifest.json", manifest)
    summary = _summary_payload(
        dataset=dataset,
        output_dir=output_dir,
        primary_timeframe=primary_timeframe,
        model_kind=model_kind,
        manifest=manifest,
        target_coverage=target_coverage,
        target_missing_reasons=target_missing_reasons,
        roll_summary=roll_summary,
        roll_assertions=roll_assertions,
        regime_deciles=regime_deciles,
        selected_cells=selected_cells,
        selector=selector,
        fold_diagnostics=fold_diagnostics,
        calibration_summary=calibration_summary,
        smoke_null=smoke_null,
        diagnostics_harness=diagnostics_harness,
        overlay=overlay,
        trade_candidates=trade_candidate_artifacts.summary,
    )
    paths["signal_research_summary"] = _write_json(output_dir / "signal_research_summary.json", summary)
    paths["signal_research_report"] = _write_text(
        output_dir / "signal_research_report.md",
        _render_signal_report(
            dataset=dataset,
            output_dir=output_dir,
            primary_timeframe=primary_timeframe,
            model_kind=model_kind,
            summary=summary,
            paths=paths,
            regime_eval=regime_eval,
        ),
    )
    return SignalResearchArtifacts(paths=paths, summary=summary)


def _target_coverage(panel: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for col in sorted(c for c in panel.columns if c.startswith("target_future_vol_expansion_")):
        suffix = col.rsplit("_", 1)[-1]
        event_col = f"target_vol_expansion_event_{suffix}"
        valid = pd.to_numeric(panel[col], errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
        events = pd.to_numeric(panel[event_col], errors="coerce").dropna() if event_col in panel else pd.Series(dtype=float)
        rows.append(
            {
                "target": col,
                "valid_rows": int(valid.shape[0]),
                "coverage": float(valid.shape[0] / panel.shape[0]) if panel.shape[0] else np.nan,
                "median_ratio": _safe(valid.median()),
                "event_rate": _safe(events.mean()),
            }
        )
    return pd.DataFrame(rows)


def _target_missing_reason_rows(
    panel: pd.DataFrame,
    dataset: ResearchDataset | None = None,
    primary_timeframe: str = "4h",
) -> pd.DataFrame:
    """Classify missing forward-target rows into deterministic, known buckets."""

    columns = sorted(c for c in panel.columns if c.startswith("target_future_vol_expansion_"))
    if panel.empty or not columns:
        return pd.DataFrame(
            columns=[
                "target",
                "ts",
                "row_index",
                "reason",
                "is_roll_boundary",
                "is_session_open",
                "is_session_close",
                "is_warmup",
                "is_tail_end_of_sample",
            ]
        )
    work = panel.sort_values("ts").reset_index(drop=True).copy()
    ts = pd.to_datetime(work["ts"], utc=True, errors="coerce") if "ts" in work else pd.Series(pd.NaT, index=work.index)
    roll_window = _roll_boundary_mask(work, dataset)
    session_open, session_close = _session_edge_masks(work)
    rows: list[dict[str, Any]] = []
    n_rows = int(work.shape[0])
    for target in columns:
        suffix = target.rsplit("_", 1)[-1]
        values = pd.to_numeric(work[target], errors="coerce").replace([np.inf, -np.inf], np.nan)
        missing = values.isna()
        if not missing.any():
            continue
        valid_positions = np.flatnonzero(values.notna().to_numpy())
        first_valid = int(valid_positions[0]) if len(valid_positions) else n_rows
        horizon_bars = _target_horizon_bars(primary_timeframe, suffix)
        tail_start = max(n_rows - horizon_bars, 0) if horizon_bars is not None else n_rows
        for idx in np.flatnonzero(missing.to_numpy()):
            is_tail = bool(idx >= tail_start)
            is_warmup = bool(idx < first_valid)
            is_roll = bool(roll_window.iloc[idx]) if idx < roll_window.shape[0] else False
            is_open = bool(session_open.iloc[idx]) if idx < session_open.shape[0] else False
            is_close = bool(session_close.iloc[idx]) if idx < session_close.shape[0] else False
            rows.append(
                {
                    "target": target,
                    "ts": ts.iloc[idx].isoformat() if not pd.isna(ts.iloc[idx]) else None,
                    "row_index": int(idx),
                    "reason": _target_missing_reason(is_tail, is_warmup, is_roll, is_open, is_close),
                    "is_roll_boundary": is_roll,
                    "is_session_open": is_open,
                    "is_session_close": is_close,
                    "is_warmup": is_warmup,
                    "is_tail_end_of_sample": is_tail,
                }
            )
    return pd.DataFrame(rows)


def _target_missing_reason_summary(missing_rows: pd.DataFrame) -> pd.DataFrame:
    if missing_rows.empty:
        return pd.DataFrame(
            columns=[
                "target",
                "reason",
                "missing_rows",
                "share_of_missing",
                "roll_boundary_rows",
                "session_open_rows",
                "session_close_rows",
                "warmup_rows",
                "tail_end_rows",
            ]
        )
    totals = missing_rows.groupby("target").size().rename("total_missing")
    summary = (
        missing_rows.groupby(["target", "reason"], dropna=False)
        .agg(
            missing_rows=("reason", "size"),
            roll_boundary_rows=("is_roll_boundary", "sum"),
            session_open_rows=("is_session_open", "sum"),
            session_close_rows=("is_session_close", "sum"),
            warmup_rows=("is_warmup", "sum"),
            tail_end_rows=("is_tail_end_of_sample", "sum"),
        )
        .reset_index()
    )
    summary = summary.merge(totals.reset_index(), on="target", how="left")
    summary["share_of_missing"] = summary["missing_rows"] / summary["total_missing"].replace(0, np.nan)
    return summary.drop(columns=["total_missing"]).sort_values(["target", "missing_rows"], ascending=[True, False])


def _target_missing_reason(
    is_tail: bool,
    is_warmup: bool,
    is_roll: bool,
    is_open: bool,
    is_close: bool,
) -> str:
    if is_tail:
        return "tail_end_of_sample"
    if is_warmup:
        return "warmup"
    if is_roll:
        return "roll_boundary"
    if is_open:
        return "session_open"
    if is_close:
        return "session_close"
    return "other"


def _roll_boundary_mask(panel: pd.DataFrame, dataset: ResearchDataset | None) -> pd.Series:
    mask = pd.Series(False, index=panel.index)
    if "expiry" in panel:
        expiry = panel["expiry"].astype(str)
        changed = expiry.ne(expiry.shift(1)) | expiry.ne(expiry.shift(-1))
        mask = mask | changed.fillna(False)
    schedule = (dataset.metadata.get("roll_schedule") if dataset is not None else None) or []
    if "ts" not in panel or not schedule:
        return mask
    ts = pd.to_datetime(panel["ts"], utc=True, errors="coerce")
    for row in schedule:
        roll_ts = pd.to_datetime(row.get("roll_date"), utc=True, errors="coerce")
        if pd.isna(roll_ts):
            continue
        near = (ts.dt.normalize() - roll_ts.normalize()).dt.days.abs().le(1)
        mask = mask | near.fillna(False)
    return mask


def _session_edge_masks(panel: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    if "session_date" not in panel:
        empty = pd.Series(False, index=panel.index)
        return empty, empty
    grouped = panel.groupby("session_date", dropna=False).cumcount()
    reverse = panel.iloc[::-1].groupby("session_date", dropna=False).cumcount().iloc[::-1]
    return grouped.eq(0), reverse.eq(0)


def _target_horizon_bars(primary_timeframe: str, suffix: str) -> int | None:
    mapping = {
        "1h": {"4h": 4, "1d": 24, "3d": 72, "5d": 120},
        "4h": {"4h": 1, "1d": 6, "3d": 18, "5d": 30},
        "1d": {"1d": 1, "3d": 3, "5d": 5},
        "daily": {"1d": 1, "3d": 3, "5d": 5},
    }
    return mapping.get(primary_timeframe.lower(), {}).get(suffix.lower())


def _roll_sensitivity(config: CLResearchConfig) -> tuple[pd.DataFrame, pd.DataFrame]:
    if config.source.lower() not in {"auto", "duckdb"} or not config.lake_path.exists():
        empty = pd.DataFrame()
        return empty, empty
    bars = _load_dated_bars(config)
    if bars.empty:
        empty = pd.DataFrame()
        return empty, empty
    policy = RollPolicy(
        name=config.continuous_roll_policy,  # type: ignore[arg-type]
        roll_window_business_days=config.continuous_roll_window_business_days,
        forced_roll_business_days_before_last_trade=config.continuous_forced_roll_business_days_before_last_trade,
        volume_crossover_sessions=config.continuous_volume_crossover_sessions,
    )
    guard = None
    weekend = construct_continuous_series(
        bars,
        symbol=config.symbol,
        policy=policy,
        adjustment=config.continuous_adjustment,  # type: ignore[arg-type]
        calendar=WeekendHolidayCalendar(),
        front_month_guard=guard,
    )
    nymex = construct_continuous_series(
        bars,
        symbol=config.symbol,
        policy=policy,
        adjustment=config.continuous_adjustment,  # type: ignore[arg-type]
        calendar=NymexObservedHolidayCalendar(),
        front_month_guard=guard,
    )
    if weekend.schedule.empty or nymex.schedule.empty:
        summary = pd.DataFrame(
            [
                {
                    "weekend_panel_rows": int(weekend.bars.shape[0]),
                    "nymex_panel_rows": int(nymex.bars.shape[0]),
                    "roll_events": 0,
                    "roll_date_changes": 0,
                    "last_trade_date_changes": 0,
                    "roll_gap_changes": 0,
                    "active_expiry_sequence_changed": False,
                    "panel_rows_changed": int(weekend.bars.shape[0]) != int(nymex.bars.shape[0]),
                }
            ]
        )
        return summary, pd.DataFrame()
    compare = weekend.schedule.add_prefix("weekend_").merge(
        nymex.schedule.add_prefix("nymex_"),
        left_on=["weekend_front_expiry", "weekend_next_expiry"],
        right_on=["nymex_front_expiry", "nymex_next_expiry"],
        how="outer",
    )
    if compare.empty:
        return pd.DataFrame(), compare
    compare["roll_date_changed"] = compare["weekend_roll_date"] != compare["nymex_roll_date"]
    compare["last_trade_date_changed"] = compare["weekend_last_trade_date"] != compare["nymex_last_trade_date"]
    compare["roll_gap_changed"] = ~np.isclose(
        pd.to_numeric(compare["weekend_roll_gap"], errors="coerce"),
        pd.to_numeric(compare["nymex_roll_gap"], errors="coerce"),
        equal_nan=True,
    )
    compare["panel_rows_changed"] = int(weekend.bars.shape[0]) != int(nymex.bars.shape[0])
    compare["active_expiry_sequence_changed"] = not weekend.bars["expiry"].reset_index(drop=True).equals(
        nymex.bars["expiry"].reset_index(drop=True)
    )
    summary = pd.DataFrame(
        [
            {
                "weekend_panel_rows": int(weekend.bars.shape[0]),
                "nymex_panel_rows": int(nymex.bars.shape[0]),
                "roll_events": int(compare.shape[0]),
                "roll_date_changes": int(compare["roll_date_changed"].sum()),
                "last_trade_date_changes": int(compare["last_trade_date_changed"].sum()),
                "roll_gap_changes": int(compare["roll_gap_changed"].sum()),
                "active_expiry_sequence_changed": bool(compare["active_expiry_sequence_changed"].any()),
                "panel_rows_changed": bool(compare["panel_rows_changed"].any()),
            }
        ]
    )
    return summary, compare


def _roll_sensitivity_assertions(summary: pd.DataFrame) -> pd.DataFrame:
    rows = [
        {
            "check_id": "roll_sensitivity_available",
            "status": "PASS" if not summary.empty else "WARN",
            "observed": bool(not summary.empty),
            "threshold": "summary must be non-empty",
            "message": "Roll sensitivity comparison was generated."
            if not summary.empty
            else "Roll sensitivity comparison is unavailable for this source/config.",
        }
    ]
    if not summary.empty:
        row = summary.iloc[0]
        sequence_changed_same_rows = bool(row.get("active_expiry_sequence_changed")) and not bool(
            row.get("panel_rows_changed")
        )
        rows.append(
            {
                "check_id": "roll_sequence_changed_same_rows",
                "status": "WARN" if sequence_changed_same_rows else "PASS",
                "observed": sequence_changed_same_rows,
                "threshold": "warn when active expiry sequence changes while row count is unchanged",
                "message": (
                    "Active-expiry sequence changed while panel row count did not; inspect calendar/roll assumptions."
                    if sequence_changed_same_rows
                    else "No internal consistency warning from roll sequence vs row-count comparison."
                ),
            }
        )
    return pd.DataFrame(rows)


def _load_dated_bars(config: CLResearchConfig) -> pd.DataFrame:
    with MinuteLake(config.lake_path) as lake:
        clauses = ["symbol = ?", "expiry != ?"]
        params: list[Any] = [config.symbol.upper(), CONTINUOUS_EXPIRY]
        if config.start_ts is not None:
            clauses.append("ts >= ?")
            params.append(pd.Timestamp(config.start_ts).to_pydatetime())
        if config.end_ts is not None:
            clauses.append("ts < ?")
            params.append(pd.Timestamp(config.end_ts).to_pydatetime())
        rows = lake.connect().execute(
            f"""
            SELECT ts, symbol, expiry, o, h, l, c, v
            FROM {lake.bars_table}
            WHERE {" AND ".join(clauses)}
            ORDER BY ts, expiry
            """,
            params,
        ).fetchall()
    return pd.DataFrame(rows, columns=["ts", "symbol", "expiry", "o", "h", "l", "c", "v"])


def _preferred_model(results: dict[str, ExpansionModelResult]) -> tuple[str, ExpansionModelResult | None]:
    for name in ("lightgbm", "logistic", "xgboost"):
        result = results.get(name)
        if result is not None and not result.predictions.empty:
            return name, result
    for name, result in results.items():
        if not result.predictions.empty:
            return name, result
    return "none", None


def _prediction_panel(panel: pd.DataFrame, predictions: pd.DataFrame) -> pd.DataFrame:
    if predictions.empty:
        return pd.DataFrame()
    keep = [
        "ts",
        "regime",
        "target_future_log_return_1d",
        "target_future_return_1d",
        "target_future_move_norm_1d",
        "target_future_vol_expansion_1d",
        "target_vol_expansion_event_1d",
        "target_tail_event_1d",
    ]
    extra = [col for col in keep if col in panel]
    out = predictions.merge(panel[extra], on="ts", how="left", suffixes=("", "_panel"))
    out["regime"] = pd.to_numeric(out["regime"], errors="coerce")
    out["decile"] = pd.qcut(out["y_prob"].rank(method="first"), q=10, labels=False, duplicates="drop")
    return out


def _regime_decile_diagnostics(joined: pd.DataFrame) -> pd.DataFrame:
    if joined.empty or "decile" not in joined:
        return pd.DataFrame()
    rows = []
    for (regime, decile), group in joined.dropna(subset=["regime", "decile"]).groupby(["regime", "decile"]):
        fwd = _numeric_col(group, "target_future_log_return_1d")
        event_rate = float(group["y_true"].mean())
        mean_probability = float(group["y_prob"].mean())
        tail_participation = _safe(_numeric_col(group, "target_tail_event_1d").mean())
        drawdown_proxy = _safe(_max_drawdown(fwd.dropna()))
        rows.append(
            {
                "regime": int(regime),
                "probability_decile": int(decile) + 1,
                "n": int(group.shape[0]),
                "mean_probability": mean_probability,
                "event_rate": event_rate,
                "tail_participation": tail_participation,
                "mean_forward_log_return_1d": _safe(fwd.mean()),
                "skew_forward_log_return_1d": _safe(fwd.skew()),
                "drawdown_proxy": drawdown_proxy,
                "mean_future_move_norm_1d": _safe(
                    _numeric_col(group, "target_future_move_norm_1d").mean()
                ),
                "convexity_research_score": _convexity_research_score(
                    event_rate=event_rate,
                    mean_probability=mean_probability,
                    tail_participation=tail_participation,
                    drawdown_proxy=drawdown_proxy,
                ),
            }
        )
    return pd.DataFrame(rows).sort_values(["regime", "probability_decile"]).reset_index(drop=True)


def _convexity_research_score(
    *,
    event_rate: float | None,
    mean_probability: float | None,
    tail_participation: float | None,
    drawdown_proxy: float | None,
) -> float | None:
    """Return the reproducible convexity research score used in report ranking.

    Formula:
    ``event_rate + mean_probability + tail_participation - abs(drawdown_proxy)``.
    Null ``tail_participation`` and ``drawdown_proxy`` are treated as zero so the
    score can be recomputed from the output columns for every selected cell.
    """

    if event_rate is None or mean_probability is None or pd.isna(event_rate) or pd.isna(mean_probability):
        return None
    tail = 0.0 if tail_participation is None or pd.isna(tail_participation) else float(tail_participation)
    drawdown = 0.0 if drawdown_proxy is None or pd.isna(drawdown_proxy) else abs(float(drawdown_proxy))
    return float(event_rate) + float(mean_probability) + tail - drawdown


def _select_top_cells(
    regime_deciles: pd.DataFrame,
    config: TopCellSelectorConfig | None = None,
    max_cells: int = 5,
) -> pd.DataFrame:
    """Select top regime/decile cells with explicit min-n, sort key, and tie-breakers."""

    cfg = config or TopCellSelectorConfig()
    if regime_deciles.empty:
        return pd.DataFrame()
    missing_sort_cols = [col for col in cfg.sort_key if col not in regime_deciles]
    if missing_sort_cols:
        raise ValueError(f"top-cell selector missing sort columns: {missing_sort_cols}")
    work = regime_deciles.copy()
    work = work[pd.to_numeric(work["n"], errors="coerce") >= cfg.min_n].copy()
    if work.empty:
        return pd.DataFrame(columns=[*regime_deciles.columns, "selector_rank"])
    work = work.sort_values(list(cfg.sort_key), ascending=list(cfg.ascending), kind="mergesort")
    out = work.head(max_cells).reset_index(drop=True)
    out.insert(0, "selector_rank", np.arange(1, out.shape[0] + 1))
    return out


def _fold_diagnostics(predictions: pd.DataFrame, bins: int = 5) -> pd.DataFrame:
    if predictions.empty:
        return pd.DataFrame()
    rows = []
    for fold, group in predictions.groupby("fold"):
        y = group["y_true"].astype(float)
        auc = _roc_auc(y, group["y_prob"].astype(float))
        calibration = _fold_calibration(group, bins)
        event_rates = calibration["event_rate"].astype(float).to_list() if not calibration.empty else []
        spearman = _spearman(calibration["bin"], calibration["event_rate"]) if not calibration.empty else None
        monotonic = bool(calibration["event_rate"].is_monotonic_increasing) if not calibration.empty else False
        rows.append(
            {
                "fold": int(fold),
                "n": int(group.shape[0]),
                "events": int(y.sum()),
                "event_rate": float(y.mean()),
                "mean_probability": float(group["y_prob"].mean()),
                "roc_auc": auc,
                "auc_below_0_50": bool(auc is not None and auc < 0.50),
                "calibration_bins": int(calibration.shape[0]),
                "calibration_event_rate_vector": json.dumps(event_rates),
                "calibration_spearman": spearman,
                "calibration_spearman_positive": bool(spearman is not None and spearman > 0.0),
                "calibration_monotonic": monotonic,
            }
        )
    return pd.DataFrame(rows)


def _fold_calibration(group: pd.DataFrame, bins: int) -> pd.DataFrame:
    work = group.copy()
    if work.empty:
        return pd.DataFrame()
    work["bin"] = pd.qcut(work["y_prob"].rank(method="first"), q=bins, labels=False, duplicates="drop")
    return work.groupby("bin").agg(event_rate=("y_true", "mean"), n=("y_true", "size")).reset_index()


def _calibration_summary(fold_diagnostics: pd.DataFrame) -> pd.DataFrame:
    if fold_diagnostics.empty:
        return pd.DataFrame(
            [
                {
                    "fold_count": 0,
                    "average_spearman": None,
                    "median_spearman": None,
                    "share_positive_spearman": None,
                    "share_monotonic": None,
                }
            ]
        )
    spearman = pd.to_numeric(fold_diagnostics["calibration_spearman"], errors="coerce").dropna()
    return pd.DataFrame(
        [
            {
                "fold_count": int(fold_diagnostics.shape[0]),
                "average_spearman": _safe(spearman.mean()) if not spearman.empty else None,
                "median_spearman": _safe(spearman.median()) if not spearman.empty else None,
                "share_positive_spearman": _safe((spearman > 0.0).mean()) if not spearman.empty else None,
                "share_monotonic": _safe(fold_diagnostics["calibration_monotonic"].astype(bool).mean()),
                "monotonic_folds": int(fold_diagnostics["calibration_monotonic"].astype(bool).sum()),
            }
        ]
    )


def _spearman(x: pd.Series, y: pd.Series) -> float | None:
    work = pd.DataFrame({"x": x, "y": y}).replace([np.inf, -np.inf], np.nan).dropna()
    if work.shape[0] < 2 or work["x"].nunique() < 2 or work["y"].nunique() < 2:
        return None
    xr = work["x"].rank(method="average")
    yr = work["y"].rank(method="average")
    corr = xr.corr(yr)
    return None if pd.isna(corr) else float(corr)


def _roc_auc(y_true: pd.Series, y_prob: pd.Series) -> float | None:
    if y_true.nunique() < 2:
        return None
    from sklearn.metrics import roc_auc_score

    return float(roc_auc_score(y_true, y_prob))


def _regime2_overlay(joined: pd.DataFrame) -> pd.DataFrame:
    if joined.empty or "regime" not in joined:
        return pd.DataFrame()
    variants = {
        "baseline_all_regimes": np.ones(joined.shape[0]),
        "exclude_regime_2": np.where(joined["regime"] == 2, 0.0, 1.0),
        "regime_2_risk_off_no_entry": np.where(joined["regime"] == 2, 0.0, 1.0),
        "regime_2_vol_size_down_50pct": np.where(joined["regime"] == 2, 0.5, 1.0),
    }
    rows = []
    total_events = float(joined["y_true"].sum())
    for name, weights in variants.items():
        w = pd.Series(weights, index=joined.index, dtype=float)
        effective_n = float(w.sum())
        event_weight = float((joined["y_true"] * w).sum())
        fwd = _numeric_col(joined, "target_future_log_return_1d").fillna(0.0) * w
        tails = _numeric_col(joined, "target_tail_event_1d").fillna(0.0)
        rows.append(
            {
                "variant": name,
                "effective_sample": effective_n,
                "sample_loss": float(1.0 - effective_n / joined.shape[0]) if joined.shape[0] else np.nan,
                "event_capture": float(event_weight / total_events) if total_events else np.nan,
                "weighted_event_rate": float(event_weight / effective_n) if effective_n else np.nan,
                "weighted_tail_participation": float((tails * w).sum() / effective_n) if effective_n else np.nan,
                "drawdown_proxy": _safe(_max_drawdown(fwd)),
                "regime2_rows_removed_or_downweighted": int((joined["regime"] == 2).sum()),
            }
        )
    return pd.DataFrame(rows)


def _smoke_null_diagnostics(predictions: pd.DataFrame, *, seed: int) -> pd.DataFrame:
    """Run deterministic null-label diagnostics against existing prediction scores."""

    if predictions.empty:
        return pd.DataFrame(
            [
                {
                    "test": "shuffled_labels",
                    "seed": seed,
                    "n": 0,
                    "roc_auc": None,
                    "auc_edge_from_0_50": None,
                    "probability_label_corr": None,
                    "event_rate": None,
                }
            ]
        )
    rng = np.random.default_rng(seed)
    y_prob = pd.to_numeric(predictions["y_prob"], errors="coerce")
    y_true = pd.to_numeric(predictions["y_true"], errors="coerce")
    valid = pd.DataFrame({"y_prob": y_prob, "y_true": y_true}).dropna()
    shuffled = valid["y_true"].to_numpy().copy()
    rng.shuffle(shuffled)
    shuffled_series = pd.Series(shuffled, index=valid.index, dtype=float)
    auc = _roc_auc(shuffled_series, valid["y_prob"].astype(float))
    corr = valid["y_prob"].astype(float).corr(shuffled_series)
    null_prob = pd.Series(float(valid["y_true"].mean()), index=valid.index)
    null_auc = _roc_auc(valid["y_true"].astype(float), null_prob)
    return pd.DataFrame(
        [
            {
                "test": "shuffled_labels",
                "seed": seed,
                "n": int(valid.shape[0]),
                "roc_auc": auc,
                "auc_edge_from_0_50": None if auc is None else float(auc - 0.50),
                "probability_label_corr": None if pd.isna(corr) else float(corr),
                "event_rate": float(shuffled_series.mean()) if not shuffled_series.empty else None,
            },
            {
                "test": "constant_base_rate_score",
                "seed": seed,
                "n": int(valid.shape[0]),
                "roc_auc": null_auc,
                "auc_edge_from_0_50": None if null_auc is None else float(null_auc - 0.50),
                "probability_label_corr": 0.0,
                "event_rate": float(valid["y_true"].mean()) if not valid.empty else None,
            },
        ]
    )


def _diagnostics_harness(
    *,
    target_missing_reasons: pd.DataFrame,
    roll_assertions: pd.DataFrame,
    fold_diagnostics: pd.DataFrame,
    calibration_summary: pd.DataFrame,
    selected_cells: pd.DataFrame,
    smoke_null: pd.DataFrame,
    thresholds: DiagnosticsThresholdConfig,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    if target_missing_reasons.empty:
        rows.append(_check("target_missing_reason_classification", "PASS", 0, "all missing targets classified"))
    else:
        known = target_missing_reasons[target_missing_reasons["reason"] != "other"]["missing_rows"].sum()
        total = target_missing_reasons["missing_rows"].sum()
        rows.append(
            _check(
                "target_missing_reason_classification",
                "PASS" if known == total else "WARN",
                f"{known}/{total}",
                "all missing target rows should map to known reasons",
                "classification emitted",
            )
        )
    for row in roll_assertions.to_dict(orient="records"):
        rows.append(_check(str(row["check_id"]), str(row["status"]), row.get("observed"), row.get("threshold"), row.get("message")))
    cal = calibration_summary.iloc[0].to_dict() if not calibration_summary.empty else {}
    share_monotonic = cal.get("share_monotonic")
    rows.append(
        _threshold_check(
            "calibration_monotonic_share",
            share_monotonic,
            thresholds.calibration_monotonic_share_min,
            warn_only=True,
            comparator=">=",
        )
    )
    rows.append(
        _threshold_check(
            "calibration_median_spearman",
            cal.get("median_spearman"),
            thresholds.calibration_spearman_median_min,
            warn_only=True,
            comparator=">=",
        )
    )
    top_n = int(pd.to_numeric(selected_cells["n"], errors="coerce").min()) if not selected_cells.empty else 0
    rows.append(
        _threshold_check(
            "top_cell_min_n",
            top_n,
            thresholds.top_cell_min_n,
            warn_only=True,
            comparator=">=",
        )
    )
    shuffled = _row_by_value(smoke_null, "test", "shuffled_labels")
    rows.append(
        _threshold_check(
            "smoke_shuffled_auc_edge_abs",
            abs(float(shuffled.get("auc_edge_from_0_50"))) if shuffled.get("auc_edge_from_0_50") is not None else None,
            thresholds.smoke_auc_edge_max_abs,
            warn_only=False,
            comparator="<=",
        )
    )
    rows.append(
        _threshold_check(
            "smoke_shuffled_prob_label_corr_abs",
            abs(float(shuffled.get("probability_label_corr"))) if shuffled.get("probability_label_corr") is not None else None,
            thresholds.smoke_probability_label_corr_max_abs,
            warn_only=False,
            comparator="<=",
        )
    )
    return pd.DataFrame(rows)


def _check(
    check_id: str,
    status: str,
    observed: Any,
    threshold: Any,
    message: str | None = None,
) -> dict[str, Any]:
    return {
        "check_id": check_id,
        "status": status.upper(),
        "observed": observed,
        "threshold": threshold,
        "message": message or "",
    }


def _threshold_check(
    check_id: str,
    observed: Any,
    threshold: float | int,
    *,
    warn_only: bool,
    comparator: str,
) -> dict[str, Any]:
    if observed is None or pd.isna(observed):
        return _check(check_id, "WARN" if warn_only else "FAIL", observed, f"{comparator} {threshold}", "metric unavailable")
    value = float(observed)
    passed = value >= float(threshold) if comparator == ">=" else value <= float(threshold)
    if passed:
        return _check(check_id, "PASS", value, f"{comparator} {threshold}", "threshold satisfied")
    return _check(
        check_id,
        "WARN" if warn_only else "FAIL",
        value,
        f"{comparator} {threshold}",
        "threshold not satisfied",
    )


def _run_manifest(
    *,
    output_dir: Path,
    dataset: ResearchDataset,
    primary_timeframe: str,
    primary_panel: pd.DataFrame,
    cl_config: CLResearchConfig,
    run_config: dict[str, Any],
    selector: TopCellSelectorConfig,
    thresholds: DiagnosticsThresholdConfig,
) -> dict[str, Any]:
    git = _git_manifest()
    return {
        "dataset_id": dataset.metadata.get("dataset_id"),
        "artifact_path": str(output_dir),
        "source_lake_path": str(cl_config.lake_path),
        "command": " ".join(sys.argv),
        "git": git,
        "python": platform.python_version(),
        "package_versions": _package_versions(["numpy", "pandas", "scikit-learn", "lightgbm", "xgboost"]),
        "dataset_hash": _dataset_hash(primary_panel),
        "random_seed_config": {
            "regime_random_state": run_config.get("regime_config", {}).get("random_state"),
            "smoke_seed": thresholds.smoke_seed,
            "tree_booster_random_state": 42,
        },
        "source_config": _jsonable(asdict(cl_config)),
        "pipeline_config": _jsonable(run_config),
        "primary_timeframe": primary_timeframe,
        "top_cell_selector": _jsonable(asdict(selector)),
        "diagnostic_thresholds": _jsonable(asdict(thresholds)),
    }


def _git_manifest() -> dict[str, Any]:
    root = Path(__file__).resolve().parents[3]
    try:
        sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()
        status = subprocess.check_output(["git", "status", "--porcelain"], cwd=root, text=True)
        return {
            "sha": sha,
            "dirty": bool(status.strip()),
            "dirty_entries": len([line for line in status.splitlines() if line.strip()]),
        }
    except Exception as exc:  # pragma: no cover - depends on local git availability
        return {"sha": None, "dirty": None, "unavailable_reason": str(exc)}


def _package_versions(names: list[str]) -> dict[str, str | None]:
    versions: dict[str, str | None] = {}
    for name in names:
        try:
            versions[name] = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:
            versions[name] = None
    return versions


def _dataset_hash(panel: pd.DataFrame) -> dict[str, Any]:
    relevant = [
        col
        for col in (
            "ts",
            "expiry",
            "c",
            "regime",
            "regime_probability",
            "target_future_vol_expansion_4h",
            "target_future_vol_expansion_1d",
            "target_vol_expansion_event_1d",
        )
        if col in panel
    ]
    work = panel[relevant].copy() if relevant else panel.copy()
    for col in work.columns:
        if pd.api.types.is_datetime64_any_dtype(work[col]):
            work[col] = pd.to_datetime(work[col], utc=True).astype("int64")
    hashed = pd.util.hash_pandas_object(work.reset_index(drop=True), index=False).to_numpy(dtype="uint64")
    digest = hashlib.sha256(hashed.tobytes()).hexdigest()
    digest = hashlib.sha256((digest + json.dumps({"columns": relevant, "rows": int(work.shape[0])})).encode()).hexdigest()
    return {"algorithm": "sha256_pandas_hash", "columns": relevant, "rows": int(work.shape[0]), "sha256": digest}


def _jsonable(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    return value


def _max_drawdown(returns: pd.Series) -> float:
    if returns.empty:
        return np.nan
    equity = np.exp(returns.cumsum())
    return float((equity / equity.cummax() - 1.0).min())


def _plot_target_coverage(frame: pd.DataFrame, path: Path, dataset: ResearchDataset, timeframe: str) -> Path:
    fig, ax = _figure()
    if not frame.empty:
        labels = frame["target"].str.replace("target_future_vol_expansion_", "", regex=False)
        ax.bar(labels, frame["coverage"])
        ax.set_ylim(0, 1.05)
    ax.set_title("Forward Vol-Expansion Target Coverage")
    ax.set_xlabel("Target horizon")
    ax.set_ylabel("Coverage share of rows")
    _caption(fig, dataset, f"Source: K2 panel {timeframe}; target coverage by horizon")
    return _save(fig, path)


def _plot_target_missing_reasons(frame: pd.DataFrame, path: Path, dataset: ResearchDataset) -> Path:
    fig, ax = _figure(figsize=(8.5, 4.8))
    if not frame.empty:
        pivot = frame.pivot_table(index="target", columns="reason", values="missing_rows", aggfunc="sum").fillna(0)
        labels = [str(label).replace("target_future_vol_expansion_", "") for label in pivot.index]
        bottom = np.zeros(len(labels))
        for reason in pivot.columns:
            values = pivot[reason].to_numpy(dtype=float)
            ax.bar(labels, values, bottom=bottom, label=str(reason))
            bottom += values
        ax.legend()
    ax.set_title("Missing Target Rows by Classified Reason")
    ax.set_xlabel("Target horizon")
    ax.set_ylabel("Missing rows")
    _caption(fig, dataset, "Source: K2 target panel; mutually exclusive primary missingness bucket")
    return _save(fig, path)


def _plot_roll_sensitivity(compare: pd.DataFrame, path: Path, dataset: ResearchDataset) -> Path:
    fig, ax = _figure(figsize=(9, 4.8))
    if not compare.empty:
        labels = compare["weekend_front_expiry"].astype(str) + "->" + compare["weekend_next_expiry"].astype(str)
        x = np.arange(compare.shape[0])
        weekend = pd.to_datetime(compare["weekend_roll_date"]).map(pd.Timestamp.toordinal)
        nymex = pd.to_datetime(compare["nymex_roll_date"]).map(pd.Timestamp.toordinal)
        ax.plot(x, weekend, marker="o", label="Weekend-only")
        ax.plot(x, nymex, marker="o", label="NYMEX holiday-aware")
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ticks = sorted(set(weekend.to_list() + nymex.to_list()))
        ax.set_yticks(ticks)
        ax.set_yticklabels([pd.Timestamp.fromordinal(int(t)).date().isoformat() for t in ticks])
        ax.legend()
    ax.set_title("CL Roll-Date Sensitivity")
    ax.set_xlabel("Roll pair")
    ax.set_ylabel("Roll date")
    _caption(fig, dataset, "Source: Volbook DuckDB dated CL bars; weekend-only vs NYMEX 2025-2026 calendar")
    return _save(fig, path)


def _plot_regime_deciles(frame: pd.DataFrame, path: Path, dataset: ResearchDataset, model_kind: str) -> Path:
    fig, ax = _figure(figsize=(9, 5))
    if not frame.empty:
        for regime, group in frame.groupby("regime"):
            ax.plot(group["probability_decile"], group["event_rate"], marker="o", label=f"Regime {regime}")
        ax.legend()
    ax.set_title("1d Vol-Expansion Event Rate by Regime and Probability Decile")
    ax.set_xlabel("Predicted probability decile")
    ax.set_ylabel("Observed event rate")
    _caption(fig, dataset, f"Source: {model_kind} walk-forward predictions; primary panel time range")
    return _save(fig, path)


def _plot_conditional_returns(joined: pd.DataFrame, path: Path, dataset: ResearchDataset, model_kind: str) -> Path:
    fig, ax = _figure(figsize=(9, 5))
    if not joined.empty:
        work = joined.dropna(subset=["decile", "target_future_log_return_1d"])
        groups = [
            pd.to_numeric(group["target_future_log_return_1d"], errors="coerce").dropna().to_numpy()
            for _, group in work.groupby("decile")
        ]
        labels = [str(int(decile) + 1) for decile, _ in work.groupby("decile")]
        if groups:
            ax.boxplot(groups, labels=labels, showfliers=False)
    ax.set_title("Conditional 1d Forward Log-Return Distribution by Probability Decile")
    ax.set_xlabel("Predicted probability decile")
    ax.set_ylabel("1d forward log return")
    _caption(fig, dataset, f"Source: {model_kind} walk-forward predictions joined to K2 targets")
    return _save(fig, path)


def _plot_fold_auc(frame: pd.DataFrame, path: Path, dataset: ResearchDataset, model_kind: str) -> Path:
    fig, ax = _figure(figsize=(8, 4.8))
    if not frame.empty:
        colors = ["tab:red" if bool(flag) else "tab:blue" for flag in frame["auc_below_0_50"]]
        ax.bar(frame["fold"].astype(str), pd.to_numeric(frame["roc_auc"], errors="coerce"), color=colors)
        ax.axhline(0.50, color="black", linestyle="--", linewidth=1)
    ax.set_title("Fold-by-Fold ROC AUC")
    ax.set_xlabel("Walk-forward fold")
    ax.set_ylabel("ROC AUC")
    _caption(fig, dataset, f"Source: {model_kind} predictions; red bars are folds below 0.50")
    return _save(fig, path)


def _plot_calibration(frame: pd.DataFrame, path: Path, dataset: ResearchDataset, model_kind: str) -> Path:
    fig, ax = _figure(figsize=(7, 5))
    if not frame.empty:
        ax.plot(frame["mean_probability"], frame["event_rate"], marker="o", label="Observed")
        low = min(frame["mean_probability"].min(), frame["event_rate"].min())
        high = max(frame["mean_probability"].max(), frame["event_rate"].max())
        ax.plot([low, high], [low, high], linestyle="--", color="black", label="Perfect calibration")
        ax.legend()
    ax.set_title("Probability Calibration for 1d Vol Expansion")
    ax.set_xlabel("Mean predicted probability")
    ax.set_ylabel("Observed event rate")
    _caption(fig, dataset, f"Source: {model_kind} walk-forward calibration bins")
    return _save(fig, path)


def _plot_calibration_spearman(
    frame: pd.DataFrame,
    path: Path,
    dataset: ResearchDataset,
    model_kind: str,
) -> Path:
    fig, ax = _figure(figsize=(8.5, 4.8))
    if not frame.empty and "calibration_spearman" in frame:
        values = pd.to_numeric(frame["calibration_spearman"], errors="coerce")
        colors = ["tab:blue" if value >= 0 else "tab:red" for value in values.fillna(0)]
        ax.bar(frame["fold"].astype(str), values, color=colors)
        ax.axhline(0.0, color="black", linestyle="--", linewidth=1)
    ax.set_title("Calibration Spearman by Fold")
    ax.set_xlabel("Walk-forward fold")
    ax.set_ylabel("Spearman(bin index, event rate)")
    _caption(fig, dataset, f"Source: {model_kind} predictions; sparse/flat folds are omitted in summary stats")
    return _save(fig, path)


def _plot_smoke_null(
    frame: pd.DataFrame,
    path: Path,
    dataset: ResearchDataset,
    model_kind: str,
) -> Path:
    fig, ax = _figure(figsize=(7.5, 4.8))
    if not frame.empty:
        values = pd.to_numeric(frame["auc_edge_from_0_50"], errors="coerce").fillna(0.0)
        x = np.arange(frame.shape[0])
        ax.bar(x, values)
        ax.set_xticks(x)
        ax.axhline(0.0, color="black", linestyle="--", linewidth=1)
        ax.set_xticklabels(frame["test"], rotation=20, ha="right")
    ax.set_title("Smoke/Null AUC Edge from 0.50")
    ax.set_xlabel("Null diagnostic")
    ax.set_ylabel("ROC AUC - 0.50")
    _caption(fig, dataset, f"Source: {model_kind} scores with deterministic null labels/scores")
    return _save(fig, path)


def _plot_diagnostics_harness(frame: pd.DataFrame, path: Path, dataset: ResearchDataset) -> Path:
    fig, ax = _figure(figsize=(8.5, 4.8))
    if not frame.empty:
        counts = frame["status"].value_counts().reindex(["PASS", "WARN", "FAIL"], fill_value=0)
        colors = ["tab:green", "tab:orange", "tab:red"]
        ax.bar(counts.index, counts.to_numpy(), color=colors)
    ax.set_title("Diagnostics Harness Status Counts")
    ax.set_xlabel("Status")
    ax.set_ylabel("Checks")
    _caption(fig, dataset, "Source: K2 report diagnostics harness")
    return _save(fig, path)


def _plot_regime2_overlay(frame: pd.DataFrame, path: Path, dataset: ResearchDataset, model_kind: str) -> Path:
    fig, ax = _figure(figsize=(9, 4.8))
    if not frame.empty:
        x = np.arange(frame.shape[0])
        ax.bar(x - 0.18, frame["event_capture"], width=0.36, label="Event capture")
        ax.bar(x + 0.18, 1.0 - frame["sample_loss"], width=0.36, label="Sample retained")
        ax.set_xticks(x)
        ax.set_xticklabels(frame["variant"], rotation=30, ha="right")
        ax.legend()
    ax.set_title("Regime 2 Overlay: Event Capture vs Sample Retained")
    ax.set_xlabel("Exploratory overlay variant")
    ax.set_ylabel("Share")
    _caption(fig, dataset, f"Source: {model_kind} predictions; sizing overlays are diagnostic weights only")
    return _save(fig, path)


def _summary_payload(
    *,
    dataset: ResearchDataset,
    output_dir: Path,
    primary_timeframe: str,
    model_kind: str,
    manifest: dict[str, Any],
    target_coverage: pd.DataFrame,
    target_missing_reasons: pd.DataFrame,
    roll_summary: pd.DataFrame,
    roll_assertions: pd.DataFrame,
    regime_deciles: pd.DataFrame,
    selected_cells: pd.DataFrame,
    selector: TopCellSelectorConfig,
    fold_diagnostics: pd.DataFrame,
    calibration_summary: pd.DataFrame,
    smoke_null: pd.DataFrame,
    diagnostics_harness: pd.DataFrame,
    overlay: pd.DataFrame,
    trade_candidates: dict[str, Any],
) -> dict[str, Any]:
    target_4h = _row_by_value(target_coverage, "target", "target_future_vol_expansion_4h")
    target_1d = _row_by_value(target_coverage, "target", "target_future_vol_expansion_1d")
    folds_below = int(fold_diagnostics["auc_below_0_50"].sum()) if not fold_diagnostics.empty else 0
    monotonic_folds = int(fold_diagnostics["calibration_monotonic"].sum()) if not fold_diagnostics.empty else 0
    return {
        "dataset_id": dataset.metadata.get("dataset_id"),
        "artifact_path": str(output_dir),
        "manifest": manifest,
        "time_range": dataset.metadata.get("bar_ranges", {}).get(primary_timeframe, {}),
        "primary_timeframe": primary_timeframe,
        "model_kind": model_kind,
        "target_future_vol_expansion_4h": target_4h,
        "target_future_vol_expansion_1d": target_1d,
        "target_missing_reasons": target_missing_reasons.to_dict(orient="records"),
        "roll_sensitivity": roll_summary.to_dict(orient="records"),
        "roll_assertions": roll_assertions.to_dict(orient="records"),
        "top_cell_selector": _jsonable(asdict(selector)),
        "top_regime_decile": selected_cells.to_dict(orient="records"),
        "fold_count": int(fold_diagnostics.shape[0]),
        "folds_below_0_50_auc": folds_below,
        "calibration_monotonic_folds": monotonic_folds,
        "calibration_spearman_by_fold": fold_diagnostics[
            ["fold", "calibration_spearman", "calibration_event_rate_vector", "calibration_monotonic"]
        ].to_dict(orient="records")
        if not fold_diagnostics.empty
        else [],
        "calibration_summary": calibration_summary.to_dict(orient="records"),
        "smoke_null_diagnostics": smoke_null.to_dict(orient="records"),
        "diagnostics_harness": diagnostics_harness.to_dict(orient="records"),
        "convexity_research_score_definition": CONVEXITY_RESEARCH_SCORE_DEFINITION,
        "regime2_overlay": overlay.to_dict(orient="records"),
        "trade_candidates": trade_candidates,
    }


def _render_signal_report(
    *,
    dataset: ResearchDataset,
    output_dir: Path,
    primary_timeframe: str,
    model_kind: str,
    summary: dict[str, Any],
    paths: dict[str, Path],
    regime_eval: RegimeEvaluation,
) -> str:
    rel = {key: str(path.relative_to(output_dir)) for key, path in paths.items()}
    target_4h = summary.get("target_future_vol_expansion_4h", {})
    target_1d = summary.get("target_future_vol_expansion_1d", {})
    roll = (summary.get("roll_sensitivity") or [{}])[0]
    top = (summary.get("top_regime_decile") or [{}])[0]
    manifest = summary.get("manifest", {})
    git = manifest.get("git", {}) if isinstance(manifest, dict) else {}
    dataset_hash = manifest.get("dataset_hash", {}) if isinstance(manifest, dict) else {}
    calibration = (summary.get("calibration_summary") or [{}])[0]
    harness = summary.get("diagnostics_harness") or []
    harness_counts = pd.DataFrame(harness)["status"].value_counts().to_dict() if harness else {}
    trade_candidates = summary.get("trade_candidates") or {}
    lines = [
        "# CL Signal Research Report",
        "",
        "This is exploratory signal research and diagnostics only. It does not define production trading, backtesting, capital allocation, entries, exits, or position sizing.",
        "",
        "## Run Manifest",
        "",
        f"- Artifact path: `{summary.get('artifact_path')}`",
        f"- Command: `{manifest.get('command')}`",
        f"- Source lake path: `{manifest.get('source_lake_path')}`",
        f"- Git SHA: `{git.get('sha')}`; dirty: `{git.get('dirty')}`; dirty entries: `{git.get('dirty_entries')}`",
        f"- Dataset hash: `{dataset_hash.get('sha256')}` over `{dataset_hash.get('rows')}` rows and columns `{dataset_hash.get('columns')}`",
        f"- Random/diagnostic seeds: `{manifest.get('random_seed_config')}`",
        f"- Package versions: `{manifest.get('package_versions')}`",
        f"- Manifest JSON: `{rel['run_manifest']}`",
        "",
        "## Sequential Completion Status",
        "",
        "- Point 1 complete: 4h vol-expansion target generation now has non-null one-bar coverage using an RMS forward realized-vol estimator.",
        "- Point 2 complete: CL roll logic supports a NYMEX observed holiday calendar for the 2025-2026 window and compares it with weekend-only rolls.",
        "- Point 3 complete: regime-conditioned 1d vol-expansion diagnostics are written by probability decile with explicit selector and reproducible research-score fields.",
        "- Point 4 complete: fold-by-fold AUC, event counts/rates, calibration monotonicity, Spearman vectors, and calibration graphics are integrated.",
        "- Point 5 complete: regime 2 is tested as exclusion, risk-off/no-entry, and 50% volatility-size-down diagnostic overlays.",
        "- Template-hardening diagnostics complete: manifest, target missingness reasons, roll consistency assertions, smoke/null checks, and diagnostics harness artifacts are integrated.",
        "",
        "## Dataset And Model",
        "",
        f"- Dataset: `{dataset.metadata.get('dataset_id')}`",
        f"- Primary timeframe: `{primary_timeframe}`",
        f"- Model used for report diagnostics: `{model_kind}`",
        f"- Time range: `{summary.get('time_range')}`",
        f"- Roll calendar in main pipeline metadata: `{dataset.metadata.get('roll_rule', {}).get('calendar')}`",
        "",
        "## Point 1: Target Coverage",
        "",
        f"- `target_future_vol_expansion_4h`: coverage `{_fmt(target_4h.get('coverage'))}`, valid rows `{target_4h.get('valid_rows')}`, event rate `{_fmt(target_4h.get('event_rate'))}`.",
        f"- `target_future_vol_expansion_1d`: coverage `{_fmt(target_1d.get('coverage'))}`, valid rows `{target_1d.get('valid_rows')}`, event rate `{_fmt(target_1d.get('event_rate'))}`.",
        f"- Graphic: `graphics/{Path(rel['target_coverage_chart']).name}`",
        f"- Missing-target reason artifacts: `{rel['target_missing_reasons']}`, `{rel['target_missing_rows']}`",
        f"- Missing-target reason graphic: `graphics/{Path(rel['target_missing_reasons_chart']).name}`",
        "",
        "### Target Missing-Bar Reasons",
        "",
        *_target_missing_report_lines(summary.get("target_missing_reasons") or []),
        "",
        "## Point 2: Roll Sensitivity",
        "",
        f"- Roll events compared: `{roll.get('roll_events')}`",
        f"- Roll-date changes: `{roll.get('roll_date_changes')}`",
        f"- Last-trade-date changes: `{roll.get('last_trade_date_changes')}`",
        f"- Roll-gap changes: `{roll.get('roll_gap_changes')}`",
        f"- Active-expiry sequence changed: `{roll.get('active_expiry_sequence_changed')}`",
        f"- Panel rows changed: `{roll.get('panel_rows_changed')}`",
        f"- Assertion artifact: `{rel['roll_sensitivity_assertions']}`",
        *_assertion_report_lines(summary.get("roll_assertions") or []),
        f"- Graphic: `graphics/{Path(rel['roll_sensitivity_chart']).name}`",
        "",
        "## Point 3: Regime-Conditioned Signals",
        "",
        f"- Top-cell selector configuration: `{summary.get('top_cell_selector')}`",
        f"- Selected top regime/decile cell: `{top}`",
        f"- Selected cells CSV: `{rel['selected_top_cells']}`",
        f"- Convexity research score definition: {CONVEXITY_RESEARCH_SCORE_DEFINITION}",
        f"- CSV: `{rel['regime_decile_diagnostics']}`",
        f"- Graphics: `graphics/{Path(rel['regime_event_chart']).name}`, `graphics/{Path(rel['conditional_return_chart']).name}`",
        "",
        "## Point 4: Fold Diagnostics",
        "",
        f"- Fold count: `{summary.get('fold_count')}`",
        f"- Folds below 0.50 ROC AUC: `{summary.get('folds_below_0_50_auc')}`",
        f"- Folds with monotonic calibration bins: `{summary.get('calibration_monotonic_folds')}`",
        f"- Calibration Spearman summary: average `{_fmt(calibration.get('average_spearman'))}`, median `{_fmt(calibration.get('median_spearman'))}`, share positive `{_fmt(calibration.get('share_positive_spearman'))}`, share monotonic `{_fmt(calibration.get('share_monotonic'))}`.",
        f"- Calibration summary CSV: `{rel['calibration_summary']}`",
        f"- Graphics: `graphics/{Path(rel['fold_auc_chart']).name}`, `graphics/{Path(rel['calibration_chart']).name}`, `graphics/{Path(rel['calibration_spearman_chart']).name}`",
        "",
        "## Smoke/Null Diagnostics",
        "",
        *_smoke_report_lines(summary.get("smoke_null_diagnostics") or []),
        f"- CSV: `{rel['smoke_null_diagnostics']}`",
        f"- Graphic: `graphics/{Path(rel['smoke_null_chart']).name}`",
        "",
        "## Diagnostics Harness",
        "",
        f"- Status counts: `{harness_counts}`",
        *_assertion_report_lines(harness),
        f"- CSV: `{rel['diagnostics_harness']}`",
        f"- Graphic: `graphics/{Path(rel['diagnostics_harness_chart']).name}`",
        "",
        "## Point 5: Regime 2 Overlay",
        "",
        f"- CSV: `{rel['regime2_overlay']}`",
        f"- Graphic: `graphics/{Path(rel['regime2_overlay_chart']).name}`",
        "",
        "## Trade-Candidate Research Layer",
        "",
        "This is exploratory trade-candidate research only. It does not imply live trade readiness, execution, backtesting, capital allocation, entries, exits, or position sizing.",
        f"- Action counts: `{trade_candidates.get('action_counts')}`",
        f"- Candidate CSV/JSON: `{rel['trade_candidates']}`, `{rel['trade_candidates_json']}`",
        f"- Directional diagnostics: `{rel['trade_candidate_directional_diagnostics']}`",
        f"- Summary by action/regime/decile: `{rel['trade_candidate_summary']}`",
        f"- Latest examples: `{rel['trade_candidate_examples']}`",
        f"- Candidate report: `{rel['trade_candidate_report']}`",
        f"- Charts: `graphics/{Path(rel['trade_candidate_timeline_chart']).name}`, `graphics/{Path(rel['trade_candidate_counts_chart']).name}`, `graphics/{Path(rel['trade_candidate_asymmetry_chart']).name}`, `graphics/{Path(rel['trade_candidate_forward_outcome_chart']).name}`",
        "",
        "## Regime Summary",
        "",
    ]
    if regime_eval.summary.empty:
        lines.append("- Regime summary is empty after filtering.")
    else:
        for row in regime_eval.summary.to_dict(orient="records"):
            lines.append(
                "- Regime `{regime}`: bars `{bars}`, share `{share:.3f}`, volatility `{volatility}`, "
                "max drawdown `{max_drawdown}`, tail participation `{tail_participation}`.".format(**row)
            )
    lines.extend(
        [
            "",
            "## Artifact Index",
            "",
            f"- Target coverage: `{rel['target_coverage']}`",
            f"- Target missing reasons: `{rel['target_missing_reasons']}`, `{rel['target_missing_rows']}`",
            f"- Roll sensitivity: `{rel['roll_sensitivity_summary']}`, `{rel['roll_sensitivity_compare']}`",
            f"- Roll assertions: `{rel['roll_sensitivity_assertions']}`",
            f"- Fold diagnostics: `{rel['fold_diagnostics']}`, `{rel['calibration_summary']}`",
            f"- Top-cell selector output: `{rel['selected_top_cells']}`",
            f"- Smoke/null diagnostics: `{rel['smoke_null_diagnostics']}`",
            f"- Diagnostics harness: `{rel['diagnostics_harness']}`",
            f"- Trade candidates: `{rel['trade_candidates']}`, `{rel['trade_candidate_report']}`",
            f"- Manifest JSON: `{rel['run_manifest']}`",
            f"- Summary JSON: `{rel['signal_research_summary']}`",
            "",
            "## Next Steps",
            "",
            "- Point 6: backfill more CL history before drawing strong macro conclusions.",
            "- Re-run the same diagnostics after additional dated-contract history is available.",
        ]
    )
    return "\n".join(lines) + "\n"


def _target_missing_report_lines(rows: list[dict[str, Any]]) -> list[str]:
    if not rows:
        return ["- No missing target rows were found for reported vol-expansion targets."]
    lines = []
    for row in rows:
        lines.append(
            "- `{target}` missing reason `{reason}`: rows `{missing_rows}`, share `{share}`, "
            "roll `{roll}`, session open `{open_}`, session close `{close}`, warmup `{warmup}`, tail `{tail}`.".format(
                target=row.get("target"),
                reason=row.get("reason"),
                missing_rows=row.get("missing_rows"),
                share=_fmt(row.get("share_of_missing")),
                roll=row.get("roll_boundary_rows"),
                open_=row.get("session_open_rows"),
                close=row.get("session_close_rows"),
                warmup=row.get("warmup_rows"),
                tail=row.get("tail_end_rows"),
            )
        )
    return lines


def _assertion_report_lines(rows: list[dict[str, Any]]) -> list[str]:
    if not rows:
        return ["- No assertion checks were emitted."]
    return [
        f"- `{row.get('check_id')}`: `{row.get('status')}`; observed `{row.get('observed')}`; threshold `{row.get('threshold')}`; {row.get('message', '')}"
        for row in rows
    ]


def _smoke_report_lines(rows: list[dict[str, Any]]) -> list[str]:
    if not rows:
        return ["- Smoke/null diagnostics were not available."]
    return [
        f"- `{row.get('test')}`: n `{row.get('n')}`, ROC AUC `{_fmt(row.get('roc_auc'))}`, AUC edge `{_fmt(row.get('auc_edge_from_0_50'))}`, score/label corr `{_fmt(row.get('probability_label_corr'))}`."
        for row in rows
    ]


def _figure(figsize: tuple[float, float] = (8, 4.8)):
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=figsize)
    ax.grid(True, axis="y", alpha=0.25)
    return fig, ax


def _caption(fig, dataset: ResearchDataset, text: str) -> None:
    rng = dataset.metadata.get("bar_ranges", {}).get(dataset.primary_timeframe, {})
    fig.text(
        0.01,
        0.01,
        f"{text}. Time range: {rng.get('start_ts')} to {rng.get('end_ts')}.",
        fontsize=8,
    )


def _save(fig, path: Path) -> Path:
    fig.tight_layout(rect=(0, 0.05, 1, 1))
    fig.savefig(path, dpi=160)
    import matplotlib.pyplot as plt

    plt.close(fig)
    return path


def _write_frame(frame: pd.DataFrame, path: Path) -> Path:
    return write_research_csv(frame, path)


def _write_json(path: Path, payload: Any) -> Path:
    path.write_text(json.dumps(payload, indent=2, default=str))
    return path


def _write_text(path: Path, text: str) -> Path:
    path.write_text(text)
    return path


def _safe(value: Any) -> float | None:
    if value is None or pd.isna(value):
        return None
    return float(value)


def _numeric_col(frame: pd.DataFrame, col: str) -> pd.Series:
    if col not in frame:
        return pd.Series(np.nan, index=frame.index, dtype=float)
    return pd.to_numeric(frame[col], errors="coerce")


def _fmt(value: Any) -> str:
    if value is None or pd.isna(value):
        return "NA"
    return f"{float(value):.4f}"


def _row_by_value(frame: pd.DataFrame, col: str, value: str) -> dict[str, Any]:
    if frame.empty or col not in frame:
        return {}
    hit = frame[frame[col] == value]
    return hit.iloc[0].to_dict() if not hit.empty else {}
